= About Designing Mule Apps
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:



In Design Center, you create a Mule application as a project having one or more flows. A flow consists of a sequence of _cards_, each card representing a connector, core Mule Runtime component, API, or module. Each card receives an input, carries out a specific function, and then sends the output of that function to the next card in the flow.

Connectors represent other applications, such as Salesforce, Slack, a database, Marketo, NetSuite, and many other applications. You configure them to tell Design Center where an application is located, how to connect to it, and which operation to perform with the application. Some connectors have operations that you can use a triggers for flows. All connectors have operations that receive an input from a flow and perform an action, such as deleting rows from databases, sending emails, and more.

Core Mule Runtime components represent functionality that is available in Mule Runtime. For example, you can use the Transform component to change the output of a card to a data type that the next card in a flow can accept. You can use the Choice component to choose which branch of a flow data should take, the choice being determined by the data itself.

Examples of triggers:

* An HTTP listener receives an incoming HTTP request.

* A Scheduler starts a flow at a configured time or or after an elapsed time.

* A Flow Ref in one flow starts another flow by referencing its name. A flow needs a trigger unless started by a Flow Ref in another flow.


== See also

* xref:4.1@mule-runtime::about-components.adoc[About Mule Components]
* xref:connectors::index.adoc[Connectors and Modules (for Mule 4)]
* xref:4.1@mule-runtime::mule-application-about.adoc[Mule Applications]
* xref:4.1@mule-runtime::about-mule-event.adoc[Mule Events]
* xref:4.1@mule-runtime::about-mule-message.adoc[Mule Messages]
* xref:4.1@mule-runtime::about-components.adoc[Components]
* xref:4.1@mule-runtime::about-flows.adoc[Flows]
