= About Mule Flow Design (Design Center)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

In Design Center, you create a Mule application in a project having one or more flows. A flow typically consists of one trigger and one or more connectors, components, or APIs.

A flow performs operations specified by its components when triggered. For example:

* An HTTP listener at the beginning of a flow gets an outside event, an incoming HTTP request, which starts the flow.
* A Scheduler at the beginning of a flow starts the flow at a configured time or restarts the flow after an elapsed time.
* A Flow Ref in one flow starts another flow by referencing its name. A flow needs a trigger unless started by a Flow Ref in another flow.

Each component receives an input, carries out a specific function, and then transfers the output to the next part of the flow. The placement of components in a flow affects functionality.

For a tutorial that will help you get started building Mule applications, see "To Create a Basic Mule Application", which is linked to from the *See also* section at the end of this topic.


== See also

* xref:create-basic-app-task.adoc.adoc[To Create a Basic Mule Application (Design Center)]
* xref:4.1@mule-runtime::about-components.adoc[About Mule Components]
* xref:connectors.adoc.adoc::index.adoc[Connectors and Modules (for Mule 4)]
* xref:4.1@mule-runtime::mule-application-about.adoc[About Mule Applications]
* xref:4.1@mule-runtime::about-mule-event.adoc[About Mule Events]
* xref:4.1@mule-runtime::about-mule-message.adoc[About Mule Messages]
* xref:4.1@mule-runtime::about-components.adoc[About Components]
* xref:4.1@mule-runtime::about-flows.adoc[About Flows]
