= Flow Designer
:page-support-status: eolReached
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:page-aliases: flow-design-reference.adoc, run-app-design-env-design-center.adoc
:imagesdir: ../assets/images

In Flow Designer, you create Mule applications to integrate systems into workflows. You create them as projects that have one or more flows. A project contains the flows for one Mule application. A _flow_ consists of a sequence of _cards_, with each card representing a core component, connector, module, or API. Each card receives input data, carries out a specific task that makes use of the input data, and then sends the output data from that task to the next card in the flow. The final card in a flow is usually one that sends a notification that the Mule application has completed its task or that sends data.

== Getting Started

To learn about Flow Designer by building an example Mule application, you can try the tutorial xref:salesforce-to-twilio.adoc[Create Your First Mule Application with Flow Designer]. The tutorial guides you in creating a Mule app that places bulk orders for company swag automatically when opportunities are closed, and that notifies customers via SMS about their order status and ETA.

To start creating Mule applications:

* Try the easiest option, which is to import a template into Flow Designer from Anypoint Exchange. See xref:import-template.adoc[Create a Mule Application Quickly from a Template].
* Create a new Mule-app project in Design Center and use the wizard that automatically opens to walk you through scaffolding a flow with a trigger card and a target card.
* Create a new Mule-app project and click *Go straight to the canvas* in the wizard to start building a flow from a blank canvas.



== See Also

* xref::fd-elements-of-flows.adoc[The Elements of Flows in Mule Applications]
* xref::fd-tour.adoc[Tour of Flow Designer]
* xref:connectors::index.adoc[Connectors and Modules (for Mule 4)]
