= Manage an API-specification Project in GitHub

All new API-specification projects that you work on in the code editor of API Designer in Design Center can be integrated with GitHub.


. Create a new project for the code editor in API Designer and choose to save the project in GitHub. API Designer creates a repository in GitHub that has the same name as your project. As you and other people work in the project, API Designer keeps the project synchronized with the repository GitHub.
. Work as you normally do in the code editor. API Designer periodically commits your changes to the repository. You and other people in your Anypoint organization who have access to the repository can create branches to work in. API Designer immediately pushes new branches to GitHub.
+
[NOTE]
====
If another person commits changes to the same project and branch that you are working in, API Designer gives you two choices for how to proceed:
* Create a new branch for your work and thereby preserving your changes.
* Discard your changes and incorporating the changes that were made by the other person.
====
. When you are ready to have your work reviewed, you can create a pull request either from API Designer or directly within GitHub.


You must install the GitHub application into Design Center. Install once and everyone in your org who has access to API Designer can use the integration.

When you go to create a new API-specification project, if the GitHub integration application is not yet installed in Design Center, an overlay on top of the dialog asks whether you want to install it. Clicking the overlay starts the process. The screens for the installation include instructions.

In the list of projects in the Design Center, API-specification projects that are saved in GitHub are indicated the the GitHub logo.

You cannot delete a project from Design Center. You must remove it from Design Center and then delete it from GitHub.

You cannot rename a project in Design Center. You must rename it in GitHub.

You can open the project in GitHub by clicking its entry in the list of projects in Design Center and then clicking Manage in GitHub.

After you install GitHub in Design Center for your Anypoint organization, the dialog for creating a new API-specification project includes a new option: Import from GitHub. The repositories that you have access to in GitHub are listed when you select that option. You can import only API-specification projects.
