= Behavioral Headers for Simulated Calls to REST Methods
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

You can use the following headers to change the behavior of the mocking service.

== Introduce Delays into Response Times

Use the `MS2-Delay` header to indicate how many milliseconds the request should take to answer. You might want to use this header to simulate load on your server or latency in a network.

You can specify a value for this header as an integer or as a range of integers. If you specify a range, the value must have the form `min-max`. For example, given the value `500-1000`, the request will take a random time between 500 and 1000 milliseconds.

[NOTE]
====
It is possible for the delay to be longer than a single integer value or the high end of a range, depending on the latency of your network.
====

== Restrict the Range of Error Status Codes That Can Be Returned

Use the `MS2-Error-Level` header to indicate which range of error status codes the mocking service is restricted to using. You can specify one of the following three case-sensitive values:
+
* `REQUEST_ONLY`: The mocking service uses only 4XX codes.
* `SERVER_ONLY`: The mocking service uses only 5XX codes.
* `ALL`: The mocking service can use both 4XX and 5XX codes. This is the default value.

== Randomize the Probability of Receiving Particular Status Codes

Use the `MS2-Error-Rate` header to indicate the probability of getting an error status code as a response. The value for this header must be a decimal between 0 and 1.

This header works together with MS2-Status-Code, MS2-Error-Level, or both at the same time.

[cols="1,2,2", options="header"]
.How the mocking service determines which status code to respond with when you use MS2-Error-Rate
|===
|Other header used with MS2-Error-Rate
|Mocking service (MS) responds with an error code
|Mocking service does not respond with an error code

|MS2-Status-Code
|MS uses the error code specified in MS2-Status-Code.
|MS uses the non-error status code specified in MS2-Status-Code.

|MS2-Error-Level
|MS uses the first error status code that is defined for the method and that falls in the range specified for MS2-Error-Level.
|MS uses the first non-error status code that is defined for the method.

|MS2-Error-Level and MS2-Status-Code
|MS uses the first error status code that is defined for the method and that falls in the range specified for MS2-Error-Level.
|MS uses the first non-error status code that is specified in MS2-Status-Code.

|None
|MS uses the first error status code that is defined for the method.
|MS uses the first non-error status code that is defined for the method.
|===

== Generate Payload Responses for Status Codes That Don't Have Examples Defined

Use the `MS2-Randomize` header to cause the mocking service to auto-generate a payload response if no example is defined for the response.

For example, suppose that an API specification contained the definitions of this type:

----
types:
  Person:
    properties:
      id: integer
      name: string
----

If you do not provide an example, but you use the header `MS2-Randomize` set to `true` and switch on the mocking service before sending a request, the payload of the response contains an example with random values that match the data types, like this:

----
{
  "id": 98358,
  "name": "OVCKr"
}
----

Moreover, the header supports more detailed definition of types. For example, you might change your type definition to look like this:

----
types:
  Person:
    properties:
      id:
        type: integer
        minimum: 3
        maximum: 30
        multipleOf: 3
      name: string
----

If MS2-Randomize were set to `true`, the payload in the response from the mocking service might look like this, with the value of `id` conforming to the constraints:
+
----
{
  "id": 9,
  "name": "rul68"
}
----

== Test Particular Status Codes

Use the header `MS2-Status-Code` to specify the status code or codes that the mocking service can choose from for the return message. This header behaves as a filter on the list of status codes that are defined for a method. For example, suppose a method has several non-error status codes defined; if you wanted the mocking service to respond with only one of those status codes, you would specify it with this header.

[IMPORTANT]
====
If you use this header together with MS2-Error-Rate, you must specify both a non-error status code and an error status code. Separate the two status codes with a comma. For example, you might want the mocking service to return a 201 message, if there is no error, or a 401 status code, if there is an error; in this case, you would specify `201,401` for the value.
====

== Influence How the Mocking Service Selects a Status Code

By default, when the mocking service responds to a request, it chooses the minimum status code that is defined for the corresponding method. For example, if you make a POST request to an endpoint that defines responses for status codes 201, 400, 409, and 500, by default the mocking service sends the response message that is defined for the 201 status code. With the MS2-Status-Code-Selection header, you can change this default behavior or the mocking service.
+
You can combine the use of MS2-Status-Code-Selection with the use of MS2-Error-Level. The mocking service sorts in ascending numeric order the status codes that are in the range of error status codes specified by MS2-Error-Level, and then returns an error status code from that range, according to the strategy specified by MS2-Status-Code-Selection.
+
The possible values of MS2-Status-Code-Selection are:
+
`FIRST`:: The mocking service sorts the list of status codes in ascending numeric order and returns the lowest status code. For example, if the specification defines the status codes for a POST method in the order 500, 409, 400, 200, the mocking service returns the response for the 200 status code.
+
`RANDOM`:: The mocking service randomly selects one of the status codes to return. For example, if the specification defines the status codes for a POST method 500, 409, 400, 200, the mocking service returns the response for any one of them.

== Test API Specifications That Contain Errors

The `MS2-Strict-Model-Validations` header can be helpful when you are simulating calls to an API with a specification that was written before API Designer switched to its stricter parser on January 10, 2019.

When you set this header to `false`, you can use the mocking service even when the API specification contains errors.

When you set this header to `true`, the mocking service validates the specification before responding. If there is an error in the specification, the mocking service fails with that error. Otherwise, the mocking service works as usual.

== See Also

* xref:design-test-endpoints-visual-editor.adoc[Test Endpoints by Simulating Calls to Methods in the Visual Editor]
* xref:design-test-endpoints-code-editor.adoc[Test Endpoints by Simulating Calls to Methods in the Code Editor]
* xref:design-test-endpoints-rest-client.adoc[Test Endpoints with a REST Client]
* xref:design-test-endpoints-multiple-tools.adoc[Test Endpoints with cURL, HTTP, or an Application]
