= Manage an API-specification Project in GitHub

All new API-specification projects that you work on in the code editor of API Designer in Design Center can be integrated with GitHub.

== Features

* Create a new project for the code editor in API Designer and choose to save the project in GitHub. API Designer creates a repository in GitHub that has the same name as your project. As you and other people work in the project, API Designer keeps the project synchronized with the repository GitHub.
+
You can also import into API Designer API-specification projects that already exist in GitHub repositories.
+
After you create or import a project that is integrated with GitHub, the Design Center displays the GitHub logo next to the project name in the list of projects.

* Work as you normally do in the code editor. API Designer periodically commits your changes to the repository. You and other people in your Anypoint organization who have access to the repository can create branches to work in. API Designer immediately pushes new branches to GitHub.
+
If another person commits changes to the same project and branch that you are working in, API Designer gives you two choices for how to proceed:
** Create a new branch for your work and thereby preserving your changes.
** Discard your changes and incorporating the changes that were made by the other person.
* When you are ready to have your work reviewed, you can create a pull request either from API Designer or directly within GitHub.
* If you want to delete a branch or a repository, rename a project or repository, rollback commits, or manage your repositories in any way, you must do so directly in GitHub.
+
For example, to delete a project from Design Center, you remove the project from the list of projects in Design Center. The, you delete the repository in GitHub.
+
To rename a project, you must rename the repository in GitHub.

== Prerequisite

You must install the GitHub application into Design Center. Install once and everyone in your org who has access to API Designer can use the integration.

When you go to create a new API-specification project, and if the GitHub integration application is not yet installed in Design Center, an overlay on top of the dialog asks whether you want to install it. Clicking the overlay starts the process. The screens for the installation include instructions.
