= Create a DataWeave Expression in a Plain Text Field

You can create DataWeave expressions in plain text fields, mixing expressions with text or using them alone, to create dynamic values when flows are triggered at runtime. A new editor provides aids for creating expressions.

== About this task

Every card in a flow presents a list on its right side. The first entry in the list is labelled `Expression`. (Other entries in the list appear when a card is preceded by at least one other card. However, for this task, you need only the `Expression` entry.)

You can click the `Expression` entry and drop it into a text field if you want to compose a DataWeave expression within that field. If field also contains text, the result of the expression is concatenated with the text at runtime.

== Procedure

. Open the card in which you want to add a DataWeave expression to a plain text field.
. Click on `Expression` in the list on the right side of the card and drag it into the text field. When you drag it, the card highlights the borders of the fields that you can drop it into.
. Compose your expression with the help of the right side of the editor.
+
* Click payload elements, attributes, and variables to add them to the expression where the cursor is located.
+
* Click functions to add them to the expression where the cursor is located.

== See also

* xref:4.1@mule-runtime::dataweave.adoc[DataWeave Language]
