= Guide to Named Examples in RAML 1.0
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you want to use examples for a type, trait, or resource type in your RAML 1.0 API specification, you must follow these rules:

* Use the `example` facet when you include the `.yaml` file for a single example.
* Use the `examples` facet to include the `.raml` files for one or more NamedExample fragments.
* Use the `examples` facet when you include `.yaml` files that each contain a single example.

1. single example:
----
example: !include my/example.yaml
----

2. multiple examples:
----
examples:
  myExample1: !include my/example1.yaml
  myExample2: !include my/example2.yaml
----

3. named example(s):
----
examples: !include my/named-example(s).raml
----

- only 3. is a named example fragment, i.e. with a #%RAML 1.0 NamedExample header, 1. and 2. includes are all yaml files (no #%RAML... header)
- 3. can contain 1 or many examples (and we recommend many, at least 2), e.g.
----
#%RAML 1.0 NamedExample
myExample1:
  (...)
myExample2:
  (...)
----

Use the `example` facet only if you want to provide a single, unnamed example.


== Naming a single example for a type by using an `examples` facet

In the following sample files, the `examples` facet names the example `fullName`.

??? Now that I've changed the example to be correct, the section title and intro do not match it.???


.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    example: !include fragment.yaml
----

.fragment.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----


== Naming a single example for a type by using a NamedExample fragment

In the following sample files, the `examples` facet does not name the example. The NamedExample fragment names the example `fullName`.

??? Now that I've changed the example to be correct, the section title and intro do not match it.???

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples: !include fragment.yaml
----

.fragment.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----

== Naming two examples for a type by using an `examples` facet

In the following sample files, the `examples` facet names the examples `fullName` and `otherFullName`.

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples:
      fullName: !include fragment1.yaml
      otherFullName: !include fragment2.yaml
----

.fragment1.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----

.fragment2.yaml
----
givenName: "Kyung-won"
familyName: "Park"
----

== Naming two examples for a type in a NamedExample fragment

In the following sample files, the `examples` facet does not name the examples.  The NamedExample fragment names the examples `fullName` and `otherFullName`.

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples: !include fragment.raml
----

.fragment.raml
----
#%RAML 1.0 NamedExample
fullName:
  givenName: ”Chiaki”
  familyName: "Mukai"

otherFullName:
  givenName: "Kyung-won"
  familyName: "Park"
----

== Naming an example in the definition of a trait

When you name an example in a trait, you can name the example either in the `examples` facet or in a NamedExample fragment. If you choose to name the example in the facet, do not declare the fragment to be a NamedExample fragment.

In this case, the example is named in the NamedExample fragment.

??? Now that I've changed the example to be correct, the section title and intro do not match it.???


.api.raml
----
#%RAML 1.0
title: test
traits:
  myTrait:
    responses:
      200:
        description: desc
        body:
          application/json:
            type:
              properties:
                givenName: string
                familyName: string
            examples: !include fragment.yaml

/end:
  post:
    is: myTrait
----

.fragment.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----

== Naming an example in the definition of a resource type

When you name an example in a resource type, you can name the example either in the `examples` facet or in a NamedExample fragment. If you choose to name the example in the facet, do not declare the fragment to be a NamedExample fragment.

In this case, the example is named in the NamedExample fragment.

??? Now that I've changed the example to be correct, the section title and intro do not match it.???


.api.raml
----
#%RAML 1.0
title: test
resourceTypes:
  myResourceType:
    get:
      body:
        application/json:
          type:
            properties:
              givenName: string
              familyName: string
          examples: <<myParam>>

/end:
  type:
    myResourceType:
      myParam: !include fragment.yaml
----

.fragment.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----

== Using a single, unnamed example

If you do not want to use more than one example and you do not want to name your single example, use the `example` facet instead of the `examples` facet.

In the following example, the `example` facet includes `fragment1.yaml`. Neither the facet nor the fragment names the example.

If you want the `example` facet to point to `fragment2.raml`, you must change the filename in the facet. You cannot include both fragments at the same time.

???The point in this section is now explained in the intro to this topic.???

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
   example: !include fragment1.yaml
----

.fragment1.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----

.fragment2.yaml
----
givenName: "Kyung-won"
familyName: "Park"
----


[NOTE]
====
The reason for using `.yaml` files for the examples and not `.raml` files is that, according to the RAML 1.0 specification, a NamedExample fragment that defines only one example is not valid. Therefore, you should not use NamedExample fragments when you are using single, unnamed examples.

For example, the following NamedExample fragments are invalid:

.fragment1.raml
----
#%RAML 1.0 NamedExample
givenName: ”Chiaki”
familyName: "Mukai"
----

.fragment2.raml
----
#%RAML 1.0 NamedExample
givenName: "Kyung-won"
familyName: "Park"
----

API Designer ignores the header and uses the examples. However, if you validate a specification with any other RAML processors, NamedExample fragments that define only one example should generate errors, in accord with the RAML 1.0 specification.
====
