= Viewing the Documentation of a Specification or Stand-Alone Fragment
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

The right pane of the code editor presents two views that you can display one at a time: *Documentation* and *Errors & Warnings*. You can switch between the two views by clicking the buttons at the bottom of the pane.

The *Documentation* pane presents the documentation of an API specification (including the documentation of its fragments) or supported stand-alone fragment in a structured display. Click the navigation icon just above the top-left corner of the pane to show a list of the endpoints, methods, security schemes, documentation items, and types that are in a specification. Click an item in the list to see the item's documentation.

There are several different types of documentation that you can display:

* A summary of a specification
+
Includes the list of all of the endpoints in the specification and the methods for accessing them.

* Documentation of an endpoint
+
Includes the URI for accessing the endpoint (using the base URI that is defined in the specification), a description of the endpoint (if the specification defines one), and a list of the HTTP methods that can access the endpoint.

* Documentation of an HTTP method
+
Includes the URI for sending requests (using the base URI that is defined in the specification), a description of the method (if the specification defines one), and other information, such as the different responses that the specification defines for a method.

* Documentation of types
+
Includes their names, data types, descriptions (if the specification or fragment defines them), accepted values (if the types are enums), and more.

* Documentation of security schemes
+
Includes the type of scheme and the required authorization information.

* The content of `documentation` fragments
+
Includes the title and content of each fragment.


== See Also

xref:design-doc-spec-toc.adoc[The Table of Contents for an API Specification]
