= View the Source Project for Assets Published to Exchange

After publishing an asset to Anypoint Exchange, you can view the source files in the API Designer. Exchange provides a direct link to the API Designer project containing the source files.

When you publish a project to Exchange via a ZIP file or other resource outside of API Designer, you can only view the contents of the project. To edit the files, create a new project based on the contents of the file. If you delete a project from API Designer after publishing it to Exchange, you can only view it in read-only mode.


== Procedure

. Open your API specification or fragment in Anypoint Exchange.
. Next to the version of the specifcation or fragment you want to view, click the *︙* drop-down menu.
+
[NOTE]
====
You can only view older published versions of a specification or fragment published to Exchange. You cannot edit them.
====
+
Alternatively, you can the most recent version of a specifcation or fragment by clicking *︙* in the asset toolbar and selecting *View code*.

. Select *View code in API Designer*.
+
API Designer opens the project containing the specification or fragment in read-only view.

. To edit the files in the project, click *Edit spec*.
+
This option is only available if you have edit permissions on the project and the project exists in API Designer.
+
If the project was edited after being published to Exchange, API Designer gives you the option to continue edit the newer version or view the version published to Exchange.

== See Also

* xref:design-publish.adoc[Publish an API Specification]