= Create an API Specification with the Visual API Editor

You can use API Designer's visual API editor to scaffold API specifications in RAML 1.0 or in OAS 2.0 or 3.0 (JSON). You do so by populating language-neutral forms.

== Before You Begin

Within Anypoint Platform, your user ID must be assigned the _Design Center Developer_ permission.

== About this task

The visual API editor is divided into three panels:

=== The Left Panel

This panel displays the the name of the API specification being developed. It also provides controls that allow you to create resources, data types, and security schemes. These components all are included within the body of the specification and are not created as separate files.

=== The Middle Panel

This panel presents the forms in which you specify the properties of the components of the specification. When the editor first opens, it displays a form for specifying the main properties of the specification and for documenting it. Click on the name of an item in the left panel to open its form in the middle panel.

=== The Right Panel

This displays the RAML Viewer and the OAS Viewer, both of which are read-only. Click the tabs at the bottom of the panel to switch between them. These viewers display the current draft of the specification in either RAML 1.0 or OAS 3.0. As you enter values in the forms that appear in the middle panel, the draft is updated with the values.

This panel also lets you run the mocking service to test endpoints that you have set up.


== Procedure

. On the *Projects* page in Design Center, click *Create new*.
. Select *New API Specificationification*.
. In the *New API Specificationification* dialog, name your project. 
+
You can change the name later, if you want to.

. Select the option *Guide me through it* to use the visual API editor.
. Click *Create API Spec.*

_Result:_
+
The visual API editor opens.
+
As you make progress, you can run the mocking service to simulate calls to your API specification. For more information, view the topic "Simulate Calls to an API", which is listed in the *See Also* section at the end of this topic.
+
If at any time you want to edit the specification directly or customize it (import RAML fragments and more), click *Edit RAML*  or *Edit OAS* to switch to the API editor. After you switch, however, you cannot switch back to the visual API editor to continue creating the API specification.


== What to Do Next

If you are satisfied with your API specification, you can publish it to Exchange in RAML 1.0. See xref:design-publish.adoc[Publish an API Specification].

Alternatively, you can customize the specification in the API editor by clicking *Edit RAML*  or *Edit OAS*.

== See Also
* xref:design-mocking-service.adoc[Simulate Calls to an API]
* xref:design-publish.adoc[Publish an API Specification]
* xref:design-rename-project.adoc[Rename an Open Project]
* xref:design-delete-project.adoc[Delete an Open Project]
