= Set User Access Permissions

Design Center provides multiple ways to set up access management to provide collaboration across teams. 

Depending on your organization's permission structure, you can assign permissions using the xref:access-management::teams.adoc[Teams] feature, the xref:access-management::users.adoc#roles[Roles] feature (deprecated), or by assigning an xref:access-management::users.adoc#grant-user-permissions[individual user permission].

== Design Center Permissions

=== Business Group Permissions

Design Center Developer:: Enables users to view, create, and manage all projects within a business group. Use this permission to set up administrators for all the projects within a specific business group.
Design Center Creator:: Enables users to create projects in Design Center from the navigation panel and view all projects created or shared with the user. Use this permission to invite users to create, edit, and maintain your projects.
Design Center Viewer:: Enables users to view all Design Center projects within a business group and test projects with the Mocking Service. Users with this permission cannot create new projects, edit or rename existing projects, or share projects with another user. Assign this permission to those who consume your project in a specific business group.

=== Project Level Permissions

Project Administrator:: Enables users to manage and share a Design Center project within a business group. Use this permission to set up administrators for all the projects within a specific business group.
Project Editor:: Enables users to edit a Design Center project within a business group. Use this permission to invite users to create, edit, and maintain your projects.
Project Viewer:: Enables users to view a Design Center project within a business group and test projects with the Mocking Service. Users with this permission cannot create a new project, edit or rename the existing project, or share the project with another user. Assign this permission to those who consume your project in a specific business group.


NOTE: If you grant organization and project permissions, the highest permission level is the one that applies to that specific project.

== Project Views

From the Design Center home page, you can select between three types of views for your project list:

*API Projects*: Lists all the projects you have access to.
*Shared with me*: Lists only the projects shared with you by other users.

== Sharing Projects from Design Center

NOTE: You can't share Mule applications.

To share your projects and add the corresponding permissions directly from Design Center:

. On the Design Center home page, select the project.
. Click the *Share project* icon, or click *Toggle project details* icon and then click *Change access*.
.. In the *Share project* dialog box, enter the name of the user or the team in your organization to give access.
.. Select the permission level from the dropdown list. The available options are “Viewer”, “Editor”, and “Admin”.
.. Click *Save* and then click *Close*.

NOTE: This action sends the user an email informing a project has been shared with them.

== Sharing Projects from API Designer

To share your projects and add the corresponding permissions directly from API Designer:

. From the Design Center home page, click the project name link to open a project.
. Click the *Share* button.
.. In the *Share project* dialog box, enter the name of the user or the team in your organization to give access.
.. Select the permission level from the dropdown list. The available options are “Viewer”, “Editor”, and “Admin”.
.. Click *Save* and then click *Close*.

NOTE: This action sends the user an email informing a project has been shared with them.

== Changing Ownership of Projects from Design Center

If you are a project owner or an organization administrator, you can change the ownership of your projects. To change the ownership of your projects directly from Design Center:

. On the Design Center home page, select the project.
. Click the *Share project* icon, or click *Toggle project details* icon and then click *Change access*.
.. In the *Share project* dialog box, enter the name of the user in your organization to give ownership of your project.
.. Select *Transfer Ownership*  from the dropdown list.
.. Click *Save* and then click *Close*. +
_Result_: The new owner appears in the project details, and the previous owner is now granted the Project administrator permissions, as there can only be one owner per project.

== Changing Ownership of Projects from API Designer

If you are a project owner or an organization administrator, you can change the ownership of your projects. To change the ownership of your projects directly from API Designer:

. From the Design Center home page, click the project name link to open a project.
. Click the *Share* button.
.. In the *Share project* dialog box, enter the name of the user in your organization to give ownership of your project.
.. Select *Transfer Ownership* from the dropdown list.
.. Click *Save* and then click *Close*. +
_Result_: The new owner appears in the project details, and the previous owner is now granted the Project administrator permissions, as there can only be one owner per project.

== Removing Access from a Project

. Open the *Share project* dialog from API Designer or Design Center.
. For the user or team that you want to remove access to, select *Remove Access* from the dropdown list.
. Click *Close*.

