= Edit in Multiple Tabs in the Text Editor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can have multiple files open at a time in API Designer's text editor. There are four ways that you can open a file in a new tab:

* Open the context menu for a file in the file tree by clicking the three dots to its right, and then select *Open in new tab*.
* Press the Command key (MacOS) or the Control key (Windows) and click the name of the file in the file tree.
* Place your cursor in the name of a file for an `include` tag. Then, press the Command key (MacOS) or the Control key (Windows) and click the filename.
* In the errors view at the bottom of the text screen, click the link to the location of a file listed in the view.

== Navigating to Different Tabs

The tab bar appears at the top of the editor only when at least two files are open.

To switch to the tab to the left of the currently open one, follow either of these steps:
* Press Option + Shift + Tab (MacOS) or <what?> (Windows).
* Open the menu on the tab bar by clicking the ellipsis and select *Previous Tab*.

To switch to the tab to the right of the currently open one, follow either of these steps:
* Press Shift + Tab (MacOS) or <what?> (Windows).
* Open the menu on the tab bar by clicking the ellipsis and select *Next Tab*.

== Closing Tabs

To close a single tab, click the X icon that appears on it.

To close all tabs but the currently open one, click the ellipsis on the right side of the tab bar and select *Close All Other Tabs*.
