= Add Documentation to an API Specification
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

// 8/23/19: I very much need to see what an OAS spec looks like in APIC. The OAS specs that Kieran pointed me to on Google Drive are all 3.0.0, and APID does not support that version. In Slack on #api-designer-eng, I asked for OAS specs that APID supports: https://mulesoft.slack.com/archives/G1UVDDN8P/p1566585045000100?thread_ts=1565714204.001400&cid=G1UVDDN8P
// I realized again today that I need OAS specs again because I was trying to describe how (at least, in RAML) types that are defined in fragments that are included in a spec with the `uses` facet are displayed in the TOC for the full spec, as well as in the TOCs for the fragments. But I realized I was describing only the behavior for RAML, not for OAS.

As you create an API specification or API fragment, you can add documentation to it, so that, after you publish the specification, other developers can learn about them. As you add your documentation in either plain text or in GitHub-flavored Markdown, you can review it in the right panel of the code editor to see how it is rendered, ensure that it is rendered correctly, and ensure that it says what you want it to say.
////
Problems:
1. "You can add documentation to it": needs to be more detailed. You can add descriptions to types, methods, and other ... , so that other developers can understand what they are for."
2. Need to explain that the Documentation pane adds much dynamic text to help organize and present the specification.
3. Need to mention the Documentation pane overall gives you a way to check the structure of a spec or fragment. The documentation that you write as the developer appears within that structured presentation.
