= Modify Existing RAML API Specifications to Conform Better to RAML 0.8 or 1.0

Design Center now uses a stricter parser to validate API specifications that are written in either RAML 0.8 or 1.0. This parser identifies errors that the previous parser overlooked. Therefore, when you open an existing, published RAML API specification in the API editor, you might see error indicators in places where the editor did not display such indicators in the past.

You have until October 24, 2019 to fix all of the errors that the new parser identifies in your existing, published RAML API specifications. Until then, you can continue to republish specifications that contain these errors. However, all other types of error will, as usual, prevent you from republishing.

New, unpublished specifications must be error-free before you can publish them.

== See Also

* xref:design-correcting-common-errors-08.adoc[Common Errors in Conforming to RAML 0.8]
* xref:design-correcting-common-errors-10.adoc[Common Errors in Conforming to RAML 1.0]
