= Test Endpoints by Simulating Calls to Methods in the Code Editor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

While you are creating an API specification, you can test the endpoints that you define by using the code editor to simulate calls to them. You can test whether required query parameters are defined as required or optional, the bodies of responses are correct, and more.

== General Procedure

. Turn on the mocking service.
. Open the documentation for the method that you want to the method that you want to simulate calls to.
. Click *Try It*.
. Fill in values for required parameters, if there are any.
. Select any options that you want to add to the simulation.
+
* Add optional query parameters to test whether these are defined correctly.
* Add optional headers (why? I mean headers other than the behavioral headers.)
* For methods that send a request body, modify the body to trigger an error status code.
. Click *Send*.

*Result*:

_Describe where the response appears._
_Describe how to view the response._
_Describe that the request URL in the response section includes the proxy info for the mocking service. It is not the same URL as the request._

Example:
Original request for a GET:
https://anypoint.mulesoft.com/mocking/api/v1/links/bc88372b-f66e-47f6-a1fc-aba75de27fee/api/customers?firstName=Tim&lastName=Mit

Reported request for the GET:
https://anypoint.mulesoft.com/apiconsoleproxy/api/v1/proxy/https://anypoint.mulesoft.com/mocking/api/v1/links/bc88372b-f66e-47f6-a1fc-aba75de27fee/api/customers?firstName=Tim&lastName=Mit


== Test API Specifications That Contain Errors

In the *Headers* section, you can add the header `MS2-Strict-Model-Validations` if your specification contains errors, but you want to test it anyway.

include::partial$MS2-Strict-Model-Validations.adoc[]

== Test Particular Status Codes

In the *Headers* section, you can add the header `MS2-Status-Code` to specify a specific status code for the return message or multiple status codes, one of which will be randomly selected for the return message. This header behaves as a filter on the list of status codes that are defined for a method.

include::partial$MS2-Status-Code.adoc[]

== Generate Payload Responses for Status Codes That Don't Have Examples Defined

In the *Headers* section, you can add the header `MS2-Randomize` to generate a payload response if no example is defined for the response.

include::partial$MS2-Randomize.adoc[]


== Randomize the Probability of Receiving Particular Status Codes

In the *Headers* section, you can add the header `MS2-Error-Rate` to specify the probability of getting an error status code as a response. The value for this header must be a decimal between 0 and 1.

include::partial$MS2-Error-Rate.adoc[]


== Restrict the Range of Error Status Codes That Can Be Returned

In the *Headers* section, you can add the header `MS2-Error-Level` to indicate the range of error status codes the mocking service is restricted to using.

include::partial$MS2-Error-Level.adoc[]


== Introduce Delays into Response Times

In the *Headers* section, you can add the header `MS2-Delay` to indicate how many milliseconds the request should take to answer. You might want to use this header to simulate load on your server or latency in a network.

include::partial$MS2-Delay.adoc[]
