= Export Files from an API Project
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can export your API-specification or API-fragment project as a `.zip` file, if you want to work on it in another tool, such as API Workbench. You can also export an API specification, converting the specification from RAML 1.0 to OAS 2.0.

[NOTE]
====
When you export a API specification to an OAS .json file or .yaml file, the conversion follows the rules that are documented at  https://github.com/mulesoft/oas-raml-converter/blob/master/docs/RAML10-to-OAS20.md[_Export from RAML 1.0 to OAS 2.0_] in the documentation for Mulesoft's oas-raml-converter tool.
====

== Procedure
* If you are exporting a project, follow these steps:
+
. Next to the *Files* heading in the left pane, click the dots and select *Export*.
. Select *Project.zip* and name the `.zip` file.
. Click *Export*.

+
_Result:_ The `.zip` file is downloaded to your computer.

* If you are exporting an API specification as an OAS 2.0 file, follow these steps:
+
. In the left pane, select the API specification that you want to export.
. Next to the *Files* heading in the left pane, click the dots and select *Export*.
. Select *OAS .json* or *OAS .yaml*, depending on the format that you want to convert the specification to.
. Name the file.
. Click *Export*.

+
_Result:_ The file is downloaded to your computer.