= Add Documentation to an API Specification
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

As you create an API specification or API fragment in the code editor in API Designer, you can add documentation to it. You can write the documentation either in plain text or in GitHub-flavored Markdown.

As you document a specification or fragment, you can review the documentation in the right-hand pane, which is the *Documentation* pane. You open this pane by clicking the *Documentation* tab at the bottom of the right-hand panel of the code editor. The *Documentation* pane presents a view of your specification or fragment in a structured, hierarchical display, starting with a summary of the endpoints in an entire specification and letting you drill down into aspects of methods, types, security schemes, and more.

Therefore, the *Documentation* pane can help you to ensure that the specifications and fragments that you create include what you intend. You can even simulate calls to an API specification by using the *Try It* feature that you can open from this pane.

Because Anypoint Exchange presents the same functionality as exists in the *Documentation* pane, developers who want to evaluate a specification or fragment that you have published can review its structure and documentation exactly as you reviewed it in API Designer. Those developers can even simulate calls to API specifications published in Exchange.
