= Using Published RAML API Specifications in Studio 7._x_ and Mule Runtime 4._x_

As described in xref::design-modify-raml-specs-conform.adoc[Modify Published RAML API Specifications to Conform Completely to RAML 0.8 or 1.0], the text editor in Design Center is now (as of January 10, 2019) more precise in ensuring that the RAML in your API specifications is valid. The only way in which the changes to the editor will affect how published RAML API specifications are used in Studio 7._x_ and Mule Runtime 4._x_ will be to prevent a small percentage of cases where a specification published as valid from the text editor is flagged with invalid RAML in Studio. With the changes, the text editor and Studio will be consistent in how they check for invalid RAML.

== Scenarios involving Anypoint Studio 7._x_ and Mule Runtime 4._x_

* Both before and after the release of the changes to the text editor, in the majority of cases, a valid RAML API specification that is published to Exchange from the text editor will not be flagged with additional RAML errors when opened in Studio 7. Moreover, the implementation that is created in Studio 7 will be able to run without errors in Mule Runtime 4.
* Before and after the release of the changes to the text editor, it is possible in some cases to publish to Exchange an API specification that still has invalid RAML according to the text editor, yet open the specification in Studio 7 and see no invalid RAML flagged. Also, the implementation that is created in Studio 7 will be able to run without errors in Mule Runtime 4.
* In a very small number of cases before the release of the changes to the text editor, a RAML API specification that the text editor considers to be valid and that is published to Exchange could be flagged with additional RAML errors when opened in Studio 7. In such cases, it will not be possible to create an implementation of the API specification and then run the implementation in Mule Runtime 4. If you experience this problem, contact MuleSoft Technical Support.

== Scenarios involving Mule Runtime 4._x_

* In all cases, both before and after the release of the changes to the text editor, a valid RAML API specification that is published to Exchange from API Designer can be deployed as an API proxy in Mule Runtime 4.
