= Test Endpoints with a REST Client


== General Procedure
. In the code editor in API Designer, follow these steps:
.. Turn on the mocking service.
.. Open the documentation for the method that you want to simulate a call to.
.. Copy the URL that is at the top of the page.
. In the REST client, follow these steps:
.. Paste the URL into the client.
.. Specify values for required parameters, if there are any.
.. *Optional:* Add optional query parameters to test whether these are defined correctly.
.. *Optional:* Add optional headers (why? I mean headers other than the behavioral headers.)
.. *Optional:* For methods that send a request body, modify the body to trigger an error status code.
.. Send the request.

*Result:*


== Test API Specifications That Contain Errors

Add the header `MS2-Strict-Model-Validations` if your specification contains errors, but you want to test it anyway.

include::partial$MS2-Strict-Model-Validations.adoc[]

== Test Particular Status Codes

Add the header `MS2-Status-Code` to specify a specific status code for the return message or multiple status codes, one of which will be randomly selected for the return message. This header behaves as a filter on the list of status codes that are defined for a method.

include::partial$MS2-Status-Code.adoc[]

== Generate Payload Responses for Status Codes That Don't Have Examples Defined

Add the header `MS2-Randomize` to generate a payload response if no example is defined for the response.

include::partial$MS2-Randomize.adoc[]


== Randomize the Probability of Receiving Particular Status Codes

MS2-Error-Rate


== Restrict the Range of Error Status Codes That Can Be Returned

MS2-Error-Level


== Introduce Delays into Response Times

MS2-Delay
