= Common Errors in Conforming to RAML 0.8

When testing the new parser, MuleSoft identified ten common errors in API specifications written in RAML 0.8. The errors are explained with examples below. The errors are not listed in any particular order, such as frequency of occurrence in the sample of API specifications that MuleSoft tested.

If you see other errors in your existing, published RAML API specifications, refer to the specification for RAML 0.8.


== Common Error 1

*_Not using a data type of string for the example of a Boolean enum_*

If the values for a Boolean enum are either both strings or both Boolean values, the example of the enum must be a string. To illustrate the error, this snippet shows an example using the wrong data type.

[source,json]
----
#%RAML 0.8
title: ExampleRAML
/nob:
  head:
    responses:
      204:
        headers:
          X-NOB-Exists:
            enum: [true, false]
            example: true
----


The data type for this example is correct:


----
...
            enum: [true, false]
            example: "true"
----

The data type for this example is also correct:


----
...
            enum: ["true", "false"]
            example: "true"
----

== Common Error 2

*_Including a schema that contains invalid JSON_*

The JSON in files that are included in the value of the `schemas` property must be valid.

The first snippet includes the schema `appSwitcher.json`.  However, the second shows that there is an error in the JSON: an extra comma after the last key/value pair. The editor flags the error in the specification on the line with the `!include` statement.


----
#%RAML 0.8
title: ExampleRAML
schemas:
  - appSwitcher: !include schemas/appSwitcher.json
----


----
{
  "appMenuItems" : [
    {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "Call Center" ,
      "url" : "/home/home.jsp?tsid=02uxx00000056Sr"
    } , {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "Community" ,
      "url" : "/home/home.jsp?tsid=02uxx00000056Sw"
    } , {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "App Launcher" ,
      "url" : "/app/mgmt/applauncher/appLauncher.apexp?tsid=02uxx00000056Sx",
    }
  ]
}
----

== Common Error 3

*_Using a non-integer data type for the example of a property that is an integer_*

The data type for the example of a property that is an integer must be an integer. As an example of the error, this snippet shows that the data type of the example does not match the data type defined for `unit_price`


----
#%RAML 0.8
title: ExampleRAML

/products:
  /product/{product_id}:
    description: Get product instance details
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-03/schema",
                  "id": "http://jsonschema.net",
                  "properties": {
                      "unit_price": {
                          "type": "integer"
                      }
                  }
                }
              example: |
                {
                  "unit_price": 19.00
                }
----

As another example of the error, the data type of the example does not match the data type defined for `uriParameters`.


----
#%RAML 0.8
title: Order Entry API
/orders:
  /{id}:
    uriParameters:
      id:
        type: integer
        example: "451"
----

== Common Error 4

*_Not using a required property in the example of a schema that defines that property_*

An example of a schema that defines a required property must use that property. In this snippet, the property that is defined in the second `id` attribute is misspelled: `sfOrderId` should be `sOrderId`. The second snippet shows the example JSON response in which `sOrderId` is defined. The example, therefore, is not in fact using the required property because the property was not defined correctly.


----
#%RAML 0.8
title: ExampleRAML
/order:
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "type":"object",
                  "$schema": "http://json-schema.org/draft-03/schema",
                  "id": "http://com.mulesoft.demo.orders.get.json.order",
                  "properties":{
                      "property": {
                        "type":"string",
                        "id": "http://com.mulesoft.demo.orders.create.json.get.sfOrderId",
                        "required":true
                      }
                  }
                }
              example: |
                {
                  "anotherProp": 14523
                }
----


----
{
  "orderId": 14523,
  "sOrderId": "fadfead3524523",
  "sfAccountId": "fedfes3653635",
  "orderName": "Order From Someone",
  "total": 174.92,
  "orderType": "E-Commerce Order",
  "description": "A good order description",
  "orderDate": "04-03-1980"
}
----

== Common Error 5

*_Not using in an example of a schema the data type that the schema defines_*

For example, the schema in the following snippet defines the data type for the property `title` as an object; however, an array is used in the example of the schema.



----
#%RAML 0.8
title: ExampleRAML
schemas:
  - presentation: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "properties": {
           "title":  { "type": "string" }
         }
      }

/presentations: &presentations
  type: { typedCollection: { schema: presentation } }
  get:
    responses:
      200:
       body:
         application/json:
           example: |
             [
              {
                  "title": "Presentation Video"
              },
              {
                  "title": "Environment Spec Report"
              }
              ]

----


== Common Error 6

*_Using 0 or 1 as the value of an example of a Boolean_*

An example for a Boolean must have a value of "true" or "false". In this snippet illustrating the error, the value of the example for the form parameter `is_public` is incorrect.


----
#%RAML 0.8
title: ExampleRAML

/upload:
  post:
    description: |
      Upload a photo
    body:
      multipart/form-data:
        formParameters:
          title:
            description: The title of the photo.
          is_public:
            type: boolean
            example: 1
----

== Common Error 7

*_Using absolute paths to included files_*

Paths to included files must be relative. The following two snippets together give an example of the error. The `traits` node in the specification `api.raml` includes the file `traits.raml`, and correctly includes it with a relative path. However, the file `traits.raml` includes an example that is located in the file `common_400.example`. However, the `!include` statement uses an absolute path. The error is flagged in `api.raml` at the `traits` node.

The `!include` statement in `traits.raml` should use either `./common/common_400.example` or `common/common_400.example`, rather than the absolute path.

./api.raml

----
#%RAML 0.8
title: ExampleRAML
traits: !include ./common/traits.raml

/booking/list:
    is: [common_errors]
    post:
        body:
            application/json:
                example: {}
----

./common/traits.raml

----
- common_errors:
    responses:
      400:
        body:
          application/json:
            example: !include /common/common_400.example
----


== Common Error 8

*_Using invalid JSON in examples of JSON schemas_*

Examples of JSON schemas must be valid, unlike the example in the following snippet:


----
#%RAML 0.8
title: ExampleRAML
...
/api:
  get:
    responses:
      200:
        body:
          application/json:
            schema:
              {
                "type": "object",
                "required": true,
                "$schema": "http://json-schema.org/draft-03/schema",
                "properties": {
                  "a": {
                    "type": "boolean",
                    "required": true
                  }
                }
              }
            example:
              {
                "a: {
                  "a": ""
                }
----


== Common Error 9

*_Not providing a value for the `title` node_*

The `title` node cannot lack a value, as it does here:


----
#%RAML 0.8
title:
----

== Common Error 10

*_Not using in an example of a query parameter the data type that is in the definition of the query parameter_*

For example, if the type for a query parameter is string, then the example for the query parameter must also be string. Here, the example is an integer, but the query parameter is defined as a string.


----
#%RAML 0.8
title: ExampleRAML
/books:
  get:
    queryParameters:
      publicationYear:
        type: string
        example: 2016
----
