= Adding Dependencies to an API-Specification Project
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In projects for API specifications or API fragments, you can add RAML API fragments or
rulesets as dependencies directly from Anypoint Exchange. You cannot edit the fragments listed in your projects because they are referenced from their online location in Exchange.

If you export your project, the resulting ZIP file contains the referenced dependencies.
When someone downloads your project as RAML from Exchange,
the resulting ZIP file contains the referenced dependencies.

If you export your project to work on it in another editor, edit the referenced dependencies, 
and then try to import the project back into the text editor, the import fails.

== Add Dependencies to an API-Specification Project

To add dependencies to an API specification project:

. On the left side of the text editor, click the *Exchange dependencies* icon.
. Click the plus sign next to the dependency type that you want to import.
  You can select from the dependencies that are visible to the organizations that you belong to.

NOTE: API Designer supports a maximum of 1,000 files for dependencies, with a total file size no greater than 300 MB.
 

You can view the contents of dependencies by selecting them. When you are ready to continue work on your project, click the *Files* icon.

The files appear in the folder `exchange-modules`. The subfolders correspond to the parts of the URI for the referenced API fragment.

After you add a dependency on an API fragment or ruleset, an updated version of the fragment or ruleset is published. To reference the updated version in your project, you must update the dependency: 

. Click the *Exchange dependency* icon.
. Click the dependency.
. Select *Change version*. 
. In the *Change version* dialog, select the current version.

NOTE: When a Governance API is non-conformant, you can fix it on Design Center. Follow the previous steps to add the listed rulesets as dependencies and view the conformance messages in the Project Errors section to fix and republish your API definition.

== See Also

* xref:api-governance::find-conformance-issues.adoc[Finding API Conformance Issues in API Definitions]
