= API Designer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

In API Designer, you can use two different tools to create API specifications in RESTful API Modeling Language (RAML) 0.8 or 1.0, or according to OpenAPI specification 2.0 (OAS), and then publish those specifications to Anypoint Exchange.

API editor:: Use this tool if you do have experience with writing API specifications. It offers a larger degree of freedom for creating more complex specifications. It also displays errors and warnings as problems in your specification occur.  The steps for using this tool are described in xref:design-create-publish-api-raml-editor.adoc[Create and Publish an API Specification with the API Editor in API Designer].

Visual API editor:: Use this tool for lightweight designing and creating scaffolds. This editor does not allow you to import RAML fragments, add security schemes, or perform several of the tasks that the API editor allows. As you fill in various forms, the editor writes your API specification for you. After creating a scaffold in this editor, you can switch to the API editor to customize your specification. The steps for using this tool are described in xref:design-create-publish-api-visual-editor.adoc[Create and Publish an API Specification with the Visual API Editor in API Designer].

You can also use the API editor to create API fragments in RAML. The steps are described in xref:design-create-publish-api-fragment.adoc[Create and Publish an API Fragment in the API Editor in API Designer].
