= Guide to NamedExample Fragments

If you want to use more than one example for a type, resource type, or trait, you must name the examples. To name one or more example, you must use the `examples` facet. You can name an example either in the `examples` fact or in the NamedExample fragment.

== Naming a single example in the `examples` facet

The `examples` facet names the example `fullName`. The fragment is not declared as a NamedExample fragment because it does not provide a name.

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples:
      fullName: !include fragment.raml
----

.fragment.raml
----
#%RAML 1.0
givenName: ”Chiaki”
familyName: "Mukai"
----


== Naming a single example in a NamedExample fragment

The `examples` facet does not name the example. The NamedExample fragment names the example `fullName`.

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples: !include fragment.raml
----

.fragment.raml
----
#%RAML 1.0 NamedExample
fullName:
  givenName: ”Chiaki”
  familyName: "Mukai"
----

== Naming two examples in an `examples` facet

The `examples` facet names the examples `fullName` and `otherFullName`. The fragments are not declared as NamedExample fragments because they do not provide names.

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples:
      fullName: !include fragment1.raml
      otherFullName: !include fragment2.raml
----

.fragment1.raml
----
#%RAML 1.0
givenName: ”Chiaki”
familyName: "Mukai"
----

.fragment2.raml
----
#%RAML 1.0
givenName: "Kyung-won"
familyName: "Park"
----

== Naming two examples in a NamedExample fragment

The `examples` facet does not name the examples.  The NamedExample fragment names the examples `fullName` and `otherFullName`.

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples: !include fragment.raml
----

.fragment.raml
----
#%RAML 1.0 NamedExample
fullName:
  givenName: ”Chiaki”
  familyName: "Mukai"

otherFullName:
  givenName: "Kyung-won"
  familyName: "Park"
----

To use one example without naming it, you must use the `example` facet.
