= Publish an API Specification or RAML Fragment to Exchange



== Before you begin

Ensure that 


== Procedure

. Click the *Publish to Exchange* button, which is in the top-right corner of the screen.
. Fill in the following fields or accept the default values:
+
Name:: The name to give to the specification or fragment on Exchange. By default, the value is the name of the project.
Main file:: The name of the primary specification (if your project has more than one), the only specification in the project, or the RAML fragment.
Asset version:: The version number that appears on Exchange. This version number also is included in the three-part ID of the asset in Exchange.
API version:: (_Not applicable if you are publishing a RAML fragment_) If a version number is specified in the specification, this value matches that number; moreover, if you change the number here, API Designer changes it in the specification. If, however, the specification does not specify a version number, API Designer adds the value you specify here to the specification as the version number.
Group ID:: (_Advanced option_) The ID of the business group in which you are publishing the asset. Only those users who belong to the specified business group will see your asset on Exchange. The group ID is included in the three-part ID of the asset in Exchange.
Asset ID:: (_Advanced option_) The ID to give to the asset on Exchange. The asset ID is included in the three-part ID of the asset in Exchange.
. If you are publishing a draft of the asset and want to make it clear on Exchange that the asset is not read for use in production, expand *Show advanced* and select the *Snapshot* check box.
+
*Result:* The asset version is appended with `-SNAPSHOT`.
. Click *Publish*.
