= Using Repositories in GitHub to Store Projects
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

By default, projects that you create in API Designer are saved in Design Center. However, you can save projects as repositories in GitHub. There are two types of project that you can save in this way:

* An API-specification project that you want to work on in API Designer's text editor, not in the visual editor
* An API-fragment project

In each case, there is one GitHub repository per project.

Projects saved in GitHub are listed in Design Center together with projects that are saved in Design Center. They are indicated by the GitHub icon.

Every time that you open a project that is saved in GitHub, API Designer retrieves the current content of the main branch. Every time that you switch to a different branch, API Designer retrieves the current content of that branch.

== Install the MuleSoft Application in to Use a GitHub Organization with Your Anypoint Platform Organization

If your Anypoint Platform business organization is not yet configured to use GitHub to store API-Designer projects as repositories,

You configure GitHub as part of creating the first project that you want to store in GitHub.

=== Before You Begin

* If you are creating an API-specification project, follow steps 1 through 2d here: xref:design-create-publish-api-raml-editor.adoc[Create an API Specification with the Text Editor].
* If you are creating an API-fragment project, follow steps 1 though 2c here: xref:design-create-publish-api-fragment.adoc[Create and Publish an API Fragment].

=== Procedure
. Click *Install from GitHub*.
. Click *Install from GitHub* again.
+
Anypoint Platform takes you to GitHub to complete the installation process.
. Follow the instructions in the series of pages that appear in GitHub.

=== Result

The *Save location* field in the *New Specification* or *New Fragment* dialog displays your GitHub ID. When other users in your Anypoint Platform business org create a project for API Designer, they can select their own GitHub user ID if they want to save the project as a repo in the same GitHub organization.

=== What To Do Next

Return to the procedure that you were following: xref:design-create-publish-api-raml-editor.adoc[Create an API Specification with the Text Editor] or xref:design-create-publish-api-fragment.adoc[Create and Publish an API Fragment].

== Import a Project from GitHub

You can import an API-specification project or an API-fragment project that is stored as a repository in GitHub, whether you created the project in the text editor in API Designer or in an editor outside of API Designer.

. Open Design Center from the homepage of Anypoint Platform.
. On the *Projects* page in Design Center, click *Create* and then click *Create API Specification*.
. Click *Import* near the top of the dialog.
+
The dialog lists the projects that you can import from the GitHub organizations that your user ID belongs to.
. Select the project that you want to import.
+
If the project does not include an exchange.json file that was generated by the text editor in API Designer, a dialog is opened to ask you to specify which file is the root file of the project.

The project is imported and opened in the text editor.

== Save an Existing API Designer Project as a Repository in GitHub

If you have one or more API Designer projects that are saved in Design Center and you would like to save them instead in GitHub, follow these steps to migrate each one:

. Export a copy of a project from Design Center.
. Create in GitHub a repo for the copy of the project, but give the repo a name that is different from the name of the original project.
. Extract the content of the downloaded ZIP file.
. In the exchange.json file, edit the `name` field to match the name of the repo.
. Add the extracted content to the repository.
. Import the project from GitHub.
. Delete the original project.

== Working with Branches

The branch that you are currently working in is displayed at the top of the central pane of the text editor. Click the name of the branch to open a menu to carry out any of the following tasks:

* Switch to a different branch by clicking the name of that branch.
+
Before switching, you can view the difference between that branch and the current one.
* Create a new branch.
+
After you create a branch, the text editor switches to that branch.
* Open a pull request.
+
This option behaves exactly as the *Create Pull Request* option in GitHub Desktop. It opens a page in GitHub where you can specify the name of your pull request and add a comment before clicking *Create*.
* View the current branch on GitHub.
* Delete a branch.

== Managing Conflicting Changes

If another user commits changes to the branch in which you are working, the text editor displays a dialog to inform you and to give you two options:

* Discard your work and incorporate the commits into your open project.

== Removing from Design Center an API Designer Project that is Saved in GitHub

When you remove an API Designer project that is saved in GitHub, the project's repository is not deleted from GitHub. If you want to delete the repository, you must do so from GitHub.

. In the list of projects in Design Center, select the project that you want to remove.
+
Projects that are saved in GitHub are indicated by the GitHub icon.
. On the right side of the list of projects, click *Remove from Design Center*.


== See Also

* xref:design-change-root-file.adoc[Root Files in Projects in the Text Editor in API Designer]
