= Common Problems in Conforming Either to RAML 0.8 or 1.0

[[bookmark-a,Back to the top]]


As of January 10, 2019, the API editor (one of the two editors in Design Center's API Designer) uses stricter validation for specifications that are written in RAML. If you open in the API editor a published API specification that is written in either RAML 0.8 or RAML 1.0 and you see error or warning indicators, this list might help you to resolve the problems in your RAML.

== Declaring a URI parameter that is never used

If an API specification declares a URI parameter, but then does not use that parameter, the editor displays this warning message:

----
unused uri parameter “parameter”
----

If the parameter is declared as a base URI parameter, but is not used, then this is the warning message:
----
unused base uri parameter “parameter”
----

For example, the following API specification would generate two warning messages:

----
unused uri parameter "unusedParam"
----

----
unused base uri parameter "unusedUriParam"
----

----
#%RAML 1.0
title: test

baseUri: http://param.raml/a/{baseUriParam1}/{nonExists}/{baseUriParam2}

baseUriParameters:
 baseUriParam1:
   type: string
 baseUriParam2:
     type: string
 unusedParam:
   type: string

/endpoint/{uriParam1}/{nonExistsUri}:
 uriParameters:
   uriParam1:
     type: string
   unusedUriParam:
     type: string
----

To resolve the warning messages, you would simply need to remove the lines that declare these parameters:

----
#%RAML 1.0
title: test

baseUri: http://param.raml/a/{baseUriParam1}/{nonExists}/{baseUriParam2}

baseUriParameters:
 baseUriParam1:
   type: string
 baseUriParam2:
     type: string

/endpoint/{uriParam1}/{nonExistsUri}:
 uriParameters:
   uriParam1:
     type: string
----

<<Back to the top>>

== Not putting quotation marks around integers that are used as example values for strings

If an example value is required to be a `string`, but the value is instead an `integer`, then the editor displays this error message:

----
expecting !!str and !!int provided
----

For example, the example value for `a` must be in quotation marks for the editor to parse it as a `string`:
----
#%RAML 1.0
title: test
types:
 A:
    properties:
       a: string
       b: integer
    examples:
       a: 50
       b: 1
----

<<Back to the top>>

== Not including a property in an example

If an example is missing a property of the type that it is exemplifying, the editor displays this error message:

----
should have required property 'property name'
----

For example, the property `age` is missing in the example:

----
#%RAML 1.0
title: Example API Spec

types:
 User:
   type: object
   properties:
     firstName: string
     lastName: string
     age: integer
   example:
     firstName: John
     lastName: Smith
----

Either add the property to the example or, in the type declaration, declare the property as optional.

In this case, the property is added to the example:

----
#%RAML 1.0
title: Example API Spec

types:
 User:
   type: object
   properties:
     firstName: string
     lastName: string
     age: integer
   example:
     firstName: John
     lastName: Smith
     age: 49
----

In this case, the property is declared as optional:

----
#%RAML 1.0
title: Example API Spec

types:
 User:
   type: object
   properties:
     firstName: string
     lastName: string
     age?: integer
   example:
     firstName: John
     lastName: Smith
----

<<Back to the top>>

== Including undeclared properties in an example

If an example for a type includes one or more properties that were not in the type declaration, the editor displays this message:

----
should NOT have additional properties
----

The editor would display this message for the following API specification:

----
#%RAML 1.0
title: Example API Spec

types:
 User:
   type: object
   properties:
     firstName: string
     lastName: string
   example:
     firstName: John
     lastName: Smith
     age: 49
----

There are three different methods that you can choose from to resolve the problem:

* Delete the extra property from the example
+
----
#%RAML 1.0
title: Example API Spec

types:
 User:
   type: object
   properties:
     firstName: string
     lastName: string
   example:
     firstName: John
     lastName: Smith
----

* Add the property in the type declaration.
+
----
#%RAML 1.0
title: Example API Spec

types:
 User:
   type: object
   properties:
     firstName: string
     lastName: string
     age: integer
   example:
     firstName: John
     lastName: Smith
     age: 49
----

* Add the field `additionalProperties` with a value of `true` in the type declaration.
+
----
#%RAML 1.0
title: Example API Spec

types:
 User:
   type: object
   properties:
     firstName: string
     lastName: string
   additionalProperties: true
   example:
     firstName: John
     lastName: Smith
     age: 49
----

<<Back to the top>>

== Not declaring a media type for a payload

If the declaration of a payload does not declare a media type, the editor displays this message:

----
Payload media type is mandatory
----

For example, the editor would display this message for the following API specification:

----
#%RAML 1.0
title: Example API Spec
/media:
 get:
   responses:
     200:
       body:
         type: string
----

There are two methods that you can choose from to resolve the problem:

* Declare the media type locally in the payload declaration.
+
----
#%RAML 1.0
title: Example API Spec
/media:
 get:
   responses:
     200:
       body:
        application/json:
         type: string
----

* Specify the default media type globally for the API specification.
+
----
#%RAML 1.0
title: Example API Spec

mediaType: application/json

/media:
 get:
   responses:
     200:
       body:
         type: string
----

The following example uses both a global and a local declaration. In this case, the `mediaType` node defines acceptable media types as `application/json` and `application/xml`. The first type, `Person`, returns a body that is in either media type. However, the second type, `Another`, overrides the global declaration with a local one, and returns only a JSON body.

----
#%RAML 1.0
title: New API
mediaType: [ application/json, application/xml ]
types:
  Person:
  Another:
/list:
  get:
    responses:
      200:
        body: Person[]
/send:
  post:
    body:
      application/json:
        type: Another
----

<<Back to the top>>

== Not referencing fragments by using the `!include` tag

If an API specification uses the key `uses` to reference fragments, the editor displays this message:

----
Fragments must be imported by using '!include'
----

<<Back to the top>>


== Not applying libraries by using the `uses` key

If an API specification uses the `!include` tag to apply a library, the editor displays this message:

----
Libraries must be applied by using 'uses'
----


<<Back to the top>>
