= Common Problems Found in RAML 0.8 API Specifications

[[bookmark-a,Back to the top]]

If you open in the API editor a published API specification that is written in RAML 0.8 and you see error or warning indicators, this list might help you to resolve the problems in your RAML.

=== Not using a data type of string for the example of a Boolean enum (RAML 0.8)
// APIMF-824

Whether the values for a Boolean enum are both strings or Boolean values, the example of the enum must be a string. To illustrate the error, this snippet shows an example using the wrong data type.

----
#%RAML 0.8
title: ExampleRAML
/nob:
  head:
    responses:
      204:
        headers:
          X-NOB-Exists:
            enum: [true, false]
            example: true
----

RAML 0.8 supports enum values as strings only, not as boolean values. Also, in the example RAML above, no data type for the enum is declared. In RAML 0.8, when a data type is not declared, it is assumed to be `string`.

Therefore, the values in the enum in the incorrect example above must be in quotation marks. That's because the data type of an example must be the same as the data type of the element that it is an example of.

The last two line of the example RAML above should then be as they are in this correction:

----
...
            enum: ["true", "false"]
            example: "true"
----

<<Back to the top>>

=== Including a schema that contains invalid JSON (RAML 0.8)
// APIMF-841

The JSON in files that are included in the value of the `schemas` property must be valid.

The first snippet includes the schema `appSwitcher.json`. However, the second shows that there is an error in the JSON: at the end of the last value, there is a comma, though there should instead be a quotation mark.


----
#%RAML 0.8
title: ExampleRAML
schemas:
  - appSwitcher: !include schemas/appSwitcher.json
----


----
{
  "appMenuItems" : [
    {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "Call Center" ,
      "url" : "/home/home.jsp?tsid=02uxx00000056Sr"
    } , {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "Community" ,
      "url" : "/home/home.jsp?tsid=02uxx00000056Sw"
    } , {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "App Launcher" ,
      "url" : "/app/mgmt/applauncher/appLauncher.apexp?tsid=02uxx00000056Sx,
    }
  ]
}
----

<<Back to the top>>

=== Using a non-integer data type for the example of a property that is an integer (RAML 0.8)
// APIMF-853

The data type for the example of a property that is an integer must be an integer. As an example of the error, the data type of the example does not match the data type defined for `uriParameters`.


----
#%RAML 0.8
title: Order Entry API
/orders:
  /{id}:
    uriParameters:
      id:
        type: integer
        example: "451"
----

<<Back to the top>>

=== Not using a required property in the example of a schema that defines that property (RAML 0.8)
// APIMF-896

If a schema defines a required property, the example of that schema must use that property. In this example of the problem, the following API specification defines a response for the endpoint `/order/{id}`. The definition includes two files: `get_order_response_schema.json` and `get_order_response.json`.

----
#%RAML 0.8
title: ExampleRAML
version: 1.0
...
/order:
  displayName: Orders API
  /create:
    ...

  /{id}:
    displayName: Get Order by OrderId
    description: This operation will get an order by order ID from Salesforce.
    get:
      description: This operation returns the order from Salesforce by Fulfillment Order ID, not by the Salesforce unique ID.
      responses:
        200:
          body:
            application/json:
              schema: !include get_order_response_schema.json
              example: !include get_order_response.json

----

The file `get_order_response_schema.json` defines the property `sfOrderId` as a required property.
----
{
	"type":"object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"id": "http://com.mulesoft.demo.orders.get.json.order",
	"required":false,
	"properties":{
      ...
      "sfOrderId": {
        "type":"string",
        "id": "http://com.mulesoft.demo.orders.create.json.get.sfOrderId",
        "required":true
      },
  ...
----

The example of the schema is in `get_order_response.json`. However, the name of the required property is misspelled as `sOrderId`.

----
{
  "orderId": 14523,
  "sOrderId": "fadfead3524523",
  "sfAccountId": "fedfes3653635",
  "orderName": "Order From Manufacturing-Company, Inc.",
  "total": 174.92,
  "orderType": "E-Commerce Order",
  "description": "8 widgets",
  "orderDate": "04-03-2018"
}
----

<<Back to the top>>

=== Not using in an example of a schema the data type that the schema defines (RAML 0.8)
// APIMF-901

For example, the schema in the following snippet defines the data type for the property `title` as an object; however, an array is used in the example of the schema.



----
#%RAML 0.8
title: ExampleRAML
schemas:
  - presentation: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "properties": {
           "title":  { "type": "string" }
         }
      }

/presentations: &presentations
  type: { typedCollection: { schema: presentation } }
  get:
    responses:
      200:
       body:
         application/json:
           example: |
             [
              {
                  "title": "Presentation Video"
              },
              {
                  "title": "Environment Spec Report"
              }
              ]

----

<<Back to the top>>

=== Using 0 or 1 as the value of an example of a Boolean (RAML 0.8)
// APIMF-929

An example for a Boolean must have a value of "true" or "false". In this snippet illustrating the error, the value of the example for the form parameter `is_public` is incorrect.


----
#%RAML 0.8
title: ExampleRAML

/upload:
  post:
    description: |
      Upload a photo
    body:
      multipart/form-data:
        formParameters:
          title:
            description: The title of the photo.
          is_public:
            type: boolean
            example: 1
----

// === Common Error 7
// APIMF-1023
// *_Using absolute paths to included files_*

// Paths to included files must be relative. The following two snippets together give an example of the error. The `traits` node in the specification `api.raml` includes the file `traits.raml`, and correctly includes it with a relative path. However, the file `traits.raml` includes an example that is located in the file `common_400.example`. However, the `!include` statement uses an absolute path. The error is flagged in `api.raml` at the `traits` node.
//
// The `!include` statement in `traits.raml` should use either `./common/common_400.example` or `common/common_400.example`, rather than the absolute path.
//
// ./api.raml
//
// ----
// #%RAML 0.8
// title: ExampleRAML
// traits: !include ./common/traits.raml
//
// /booking/list:
//     is: [common_errors]
//     post:
//         body:
//             application/json:
//                 example: {}
// ----
//
// ./common/traits.raml
//
// ----
// - common_errors:
//     responses:
//       400:
//         body:
//           application/json:
//             example: !include /common/common_400.example
// ----

<<Back to the top>>

=== Using invalid JSON in examples of JSON schemas (RAML 0.8)
// APIMF-1069

Examples of JSON schemas must be valid, unlike the example in the following snippet:


----
#%RAML 0.8
title: ExampleRAML
...
/api:
  get:
    responses:
      200:
        body:
          application/json:
            schema:
              {
                "type": "object",
                "required": true,
                "$schema": "http://json-schema.org/draft-03/schema",
                "properties": {
                  "a": {
                    "type": "boolean",
                    "required": true
                  }
                }
              }
            example:
              {
                "a: {
                  "a": ""
                }
----


<<Back to the top>>

=== Not providing a value for the `title` node (RAML 0.8)
// APIMF-1083

The `title` node cannot lack a value, as it does here:


----
#%RAML 0.8
title:
----

<<Back to the top>>

=== Not using the data type of the RAML element in the example for that element (RAML 0.8)
// APIMF-1088

In all cases, the data type of an example must match the data type of the element that it is an example of.

In this incorrect snippet of RAML, a query parameter is defined as a string; however, the example of the query parameter is an integer.


----
#%RAML 0.8
title: ExampleRAML
/books:
  get:
    queryParameters:
      publicationYear:
        type: string
        example: 2016
----

<<Back to the top>>

=== Using an invalid path for a reference inside a JSON schema (RAML 0.8)
// APIMF-833

When you use the `$ref` keyword in a JSON schema, the path that you specify with it must start at the root of the schema. For example, the `$ref` keyword used for the property `input2` in the following schema uses an incorrect path to refer to the property `input`.
----
#%RAML 0.8
title: ExampleRAML
version: v1
schemas:
- authCodeResponse : |
    {
      "$schema": "http://json-schema.org/draft-04/schema",
      "properties": {
        "input": {
          "type": "string"
        },
        "input2": {
          "$ref": "input"
        }
      },
       "type": "object"
    }
----
The path must start at the root level of the schema and descend through the tree structure. This example of the schema shows the same `$ref` keyword using the correct path.
----
{
      "$schema": "http://json-schema.org/draft-04/schema",
      "properties": {
        "input": {
          "type": "string"
        },
        "input2": {
          "$ref": "#/properties/input"
        }
      },
       "type": "object"
    }

----

<<Back to the top>>


=== Using a reserved name for a schema (RAML 0.8)

If you use a reserved name as the name of a schema, the editor displays this message:
----
‘schemaName’ cannot be used to name a custom schema
----

Examples of reserved names are `string`, `object`, `integer`, `number`, and `object`. Any name that is used in the RAML specification cannot be used as the name for a schema.

For example, this API specification would cause the editor to display the message:

----
#%RAML 0.8

title: Example API Spec

schemas:
 string:
   type: string
----

To resolve the problem, you would need to use a different name in the schema declaration:

----
#%RAML 0.8

title: Example API Spec

schemas:
 customString:
   type: string
----

<<Back to the top>>
