= Guide to Defining Examples in RAML 1.0
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

When defining examples in external files for a type, trait, or resource type in your RAML 1.0 API specification, you should follow these rules:

* For a single example, you should use the `example` facet and include a `.yaml` file.
* For multiple examples, you should always use the `examples` facet and either:
** Define multiple examples, each pointing to individual `.yaml` files, with a single example per file
** Include a `.raml` file containing two or more examples defined in a single NamedExample fragment

The reason for using `.yaml` files for single examples and not `.raml` files is that, according to the RAML 1.0 specification, a NamedExample fragment that defines one example is not valid. Therefore, you should use a NamedExample fragment only to define two or more examples.

For example, the following NamedExample fragments are invalid:

.fragment1.raml
----
#%RAML 1.0 NamedExample
givenName: ”Chiaki”
familyName: "Mukai"
----

.fragment2.raml
----
#%RAML 1.0 NamedExample
givenName: "Kyung-won"
familyName: "Park"
----

API Designer ignores the header and uses the examples. However, if you validate a specification with any other RAML processors, NamedExample fragments that define only one example should generate errors, in accord with the RAML 1.0 specification.



== Using a Single Example That Is in a `.yaml` File

In the file `api.raml`, the `example` facet includes a single example that is in a `.yaml` file:

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    example: !include fragment.yaml
----

.fragment.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----


== Naming Two Examples That Are in `.yaml` Files

In the file `api.raml`, the `examples` facet names the examples `fullName` and `otherFullName`. Each of the two examples is in a `.yaml` file:

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples:
      fullName: !include fragment1.yaml
      otherFullName: !include fragment2.yaml
----

.fragment1.yaml
----
givenName: ”Chiaki”
familyName: "Mukai"
----

.fragment2.yaml
----
givenName: "Kyung-won"
familyName: "Park"
----

== Naming Two Examples That Are in a NamedExample Fragment

In the file `api.raml`, the `examples` facet does not name the examples.  The NamedExample fragment does, naming them `fullName` and `otherFullName`:

.api.raml
----
#%RAML 1.0
title: test
types:
  A:
    properties:
      givenName: string
      familyName: string
    examples: !include fragment.raml
----

.fragment.raml
----
#%RAML 1.0 NamedExample
fullName:
  givenName: ”Chiaki”
  familyName: "Mukai"

otherFullName:
  givenName: "Kyung-won"
  familyName: "Park"
----
