= Modify Published RAML API Specifications to Conform Completely to RAML 0.8 or 1.0

[[bookmark-a,Back to the top]]

As of January 10, 2019, the API editor (one of the two editors in Design Center's API Designer) uses stricter validation for specifications that are written in RAML. Therefore, it is possible that one or more of the APIs that you used previous versions of the API editor to create include invalid RAML that those previous versions did not flag.

Check your published APIs by opening them in the API editor in Design Center. You can use the guide on this page to correct a number of common RAML errors that were validated by the API editor in the past. If you see errors that this guide does not include, refer to the specifications for RAML 0.8 and 1.0, which you can read on https://raml.org/[raml.org].

In addition to checking more precisely for RAML errors, the API editor also validates regular expressions. Any invalid expressions in published API specifications that you reopen in the editor are now flagged as errors.

You have a long grace period to correct any invalid RAML and invalid regular expressions that your published API specifications might include. After the grace period expires, you will be unable to republish and redeploy API specifications in which such problems still exist.

[IMPORTANT]
====
You do not need to check any API specifications that were created with the visual API editor, the tool in API Designer with which you can create specifications by filling in forms.
====

* <<bookmark-b,Common Errors in Conforming to RAML 0.8>>
* <<bookmark-c,Common Errors in Conforming to RAML 1.0>>


[[bookmark-b,Common Errors in Conforming to RAML 0.8]]
== Common Errors in Conforming to RAML 0.8

If you open in the API editor a published API specification that is written in RAML 1.0 and you see error indicators, this list might help you to resolve the errors. If you see errors that this list does not include, refer to the specification for RAML 0.8, which you can read on https://raml.org/[raml.org].

=== Not using a data type of string for the example of a Boolean enum (RAML 0.8)
// APIMF-824

Whether the values for a Boolean enum are both strings or Boolean values, the example of the enum must be a string. To illustrate the error, this snippet shows an example using the wrong data type.

----
#%RAML 0.8
title: ExampleRAML
/nob:
  head:
    responses:
      204:
        headers:
          X-NOB-Exists:
            enum: [true, false]
            example: true
----

RAML 0.8 supports enum values as strings only, not as boolean values. Also, in the example RAML above, no data type for the enum is declared. In RAML 0.8, when a data type is not declared, it is assumed to be `string`.

Therefore, the values in the enum in the incorrect example above must be in quotation marks. That's because the data type of an example must be the same as the data type of the element that it is an example of.

The last two line of the example RAML above should then be as they are in this correction:

----
...
            enum: ["true", "false"]
            example: "true"
----

<<Back to the top>>

=== Including a schema that contains invalid JSON (RAML 0.8)
// APIMF-841

The JSON in files that are included in the value of the `schemas` property must be valid.

The first snippet includes the schema `appSwitcher.json`. However, the second shows that there is an error in the JSON: at the end of the last value, there is a comma, though there should instead be a quotation mark.


----
#%RAML 0.8
title: ExampleRAML
schemas:
  - appSwitcher: !include schemas/appSwitcher.json
----


----
{
  "appMenuItems" : [
    {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "Call Center" ,
      "url" : "/home/home.jsp?tsid=02uxx00000056Sr"
    } , {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "Community" ,
      "url" : "/home/home.jsp?tsid=02uxx00000056Sw"
    } , {
      "type" : "Tabset" ,
      "content" : null ,
      "icons" : null ,
      "colors" : null ,
      "label" : "App Launcher" ,
      "url" : "/app/mgmt/applauncher/appLauncher.apexp?tsid=02uxx00000056Sx,
    }
  ]
}
----

<<Back to the top>>

=== Using a non-integer data type for the example of a property that is an integer (RAML 0.8)
// APIMF-853

The data type for the example of a property that is an integer must be an integer. As an example of the error, the data type of the example does not match the data type defined for `uriParameters`.


----
#%RAML 0.8
title: Order Entry API
/orders:
  /{id}:
    uriParameters:
      id:
        type: integer
        example: "451"
----

<<Back to the top>>

=== Not using a required property in the example of a schema that defines that property (RAML 0.8)
// APIMF-896

If a schema defines a required property, the example of that schema must use that property. In this example of the problem, the following API specification defines a response for the endpoint `/order/{id}`. The definition includes two files: `get_order_response_schema.json` and `get_order_response.json`.

----
#%RAML 0.8
title: ExampleRAML
version: 1.0
...
/order:
  displayName: Orders API
  /create:
    ...

  /{id}:
    displayName: Get Order by OrderId
    description: This operation will get an order by order ID from Salesforce.
    get:
      description: This operation returns the order from Salesforce by Fulfillment Order ID, not by the Salesforce unique ID.
      responses:
        200:
          body:
            application/json:
              schema: !include get_order_response_schema.json
              example: !include get_order_response.json

----

The file `get_order_response_schema.json` defines the property `sfOrderId` as a required property.
----
{
	"type":"object",
	"$schema": "http://json-schema.org/draft-03/schema",
	"id": "http://com.mulesoft.demo.orders.get.json.order",
	"required":false,
	"properties":{
      ...
      "sfOrderId": {
        "type":"string",
        "id": "http://com.mulesoft.demo.orders.create.json.get.sfOrderId",
        "required":true
      },
  ...
----

The example of the schema is in `get_order_response.json`. However, the name of the required property is misspelled as `sOrderId`.

----
{
  "orderId": 14523,
  "sOrderId": "fadfead3524523",
  "sfAccountId": "fedfes3653635",
  "orderName": "Order From Manufacturing-Company, Inc.",
  "total": 174.92,
  "orderType": "E-Commerce Order",
  "description": "8 widgets",
  "orderDate": "04-03-2018"
}
----

<<Back to the top>>

=== Not using in an example of a schema the data type that the schema defines (RAML 0.8)
// APIMF-901

For example, the schema in the following snippet defines the data type for the property `title` as an object; however, an array is used in the example of the schema.



----
#%RAML 0.8
title: ExampleRAML
schemas:
  - presentation: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "properties": {
           "title":  { "type": "string" }
         }
      }

/presentations: &presentations
  type: { typedCollection: { schema: presentation } }
  get:
    responses:
      200:
       body:
         application/json:
           example: |
             [
              {
                  "title": "Presentation Video"
              },
              {
                  "title": "Environment Spec Report"
              }
              ]

----

<<Back to the top>>

=== Using 0 or 1 as the value of an example of a Boolean (RAML 0.8)
// APIMF-929

An example for a Boolean must have a value of "true" or "false". In this snippet illustrating the error, the value of the example for the form parameter `is_public` is incorrect.


----
#%RAML 0.8
title: ExampleRAML

/upload:
  post:
    description: |
      Upload a photo
    body:
      multipart/form-data:
        formParameters:
          title:
            description: The title of the photo.
          is_public:
            type: boolean
            example: 1
----

// === Common Error 7
// APIMF-1023
// *_Using absolute paths to included files_*

// Paths to included files must be relative. The following two snippets together give an example of the error. The `traits` node in the specification `api.raml` includes the file `traits.raml`, and correctly includes it with a relative path. However, the file `traits.raml` includes an example that is located in the file `common_400.example`. However, the `!include` statement uses an absolute path. The error is flagged in `api.raml` at the `traits` node.
//
// The `!include` statement in `traits.raml` should use either `./common/common_400.example` or `common/common_400.example`, rather than the absolute path.
//
// ./api.raml
//
// ----
// #%RAML 0.8
// title: ExampleRAML
// traits: !include ./common/traits.raml
//
// /booking/list:
//     is: [common_errors]
//     post:
//         body:
//             application/json:
//                 example: {}
// ----
//
// ./common/traits.raml
//
// ----
// - common_errors:
//     responses:
//       400:
//         body:
//           application/json:
//             example: !include /common/common_400.example
// ----

<<Back to the top>>

=== Using invalid JSON in examples of JSON schemas (RAML 0.8)
// APIMF-1069

Examples of JSON schemas must be valid, unlike the example in the following snippet:


----
#%RAML 0.8
title: ExampleRAML
...
/api:
  get:
    responses:
      200:
        body:
          application/json:
            schema:
              {
                "type": "object",
                "required": true,
                "$schema": "http://json-schema.org/draft-03/schema",
                "properties": {
                  "a": {
                    "type": "boolean",
                    "required": true
                  }
                }
              }
            example:
              {
                "a: {
                  "a": ""
                }
----


<<Back to the top>>

=== Not providing a value for the `title` node (RAML 0.8)
// APIMF-1083

The `title` node cannot lack a value, as it does here:


----
#%RAML 0.8
title:
----

<<Back to the top>>

=== Not using the data type of the RAML element in the example for that element (RAML 0.8)
// APIMF-1088

In all cases, the data type of an example must match the data type of the element that it is an example of.

In this incorrect snippet of RAML, a query parameter is defined as a string; however, the example of the query parameter is an integer.


----
#%RAML 0.8
title: ExampleRAML
/books:
  get:
    queryParameters:
      publicationYear:
        type: string
        example: 2016
----

<<Back to the top>>

=== Using an invalid path for a reference inside a JSON schema
// APIMF-833

When you use the `$ref` keyword in a JSON schema, the path that you specify with it must start at the root of the schema. For example, the `$ref` keyword used for the property `input2` in the following schema uses an incorrect path to refer to the property `input`.
----
#%RAML 0.8
title: ExampleRAML
version: v1
schemas:
- authCodeResponse : |
    {
      "$schema": "http://json-schema.org/draft-04/schema",
      "properties": {
        "input": {
          "type": "string"
        },
        "input2": {
          "$ref": "input"
        }
      },
       "type": "object"
    }
----
The path must start at the root level of the schema and descend through the tree structure. This example of the schema shows the same `$ref` keyword using the correct path.
----
{
      "$schema": "http://json-schema.org/draft-04/schema",
      "properties": {
        "input": {
          "type": "string"
        },
        "input2": {
          "$ref": "#/properties/input"
        }
      },
       "type": "object"
    }

----



[[bookmark-c,Common Errors in Conforming to RAML 1.0]]
== Common Errors in Conforming to RAML 1.0

If you open in the API editor a published API specification that is written in RAML 1.0 and you see error indicators, this list might help you to resolve the errors. If you see errors that this list does not include, refer to the specification for RAML 1.0, which you can read on https://raml.org/[raml.org].

=== Appending references with hash symbols to filenames in `!include` statements (RAML 1.0)
// APIMF-834

A filename cannot be followed by a hash symbol and a reference to a location within the named file. In this example snippet, `IncrementType.raml#increment` is not a valid link.

----
#%RAML 1.0 DataType

type: object
properties:
  startValue: integer
  endValue: integer
  exclusiveEndValue: boolean
  range:
    type: array
    items: !include IncrementType.raml#increment

----

If your specification contains an error of this type, but you meant to write a comment, place an empty space before the "#" symbol. If you meant to reference an element that is in the file, such references are not allowed. References to inner elements are valid only for XSD and JSON schemas.

<<Back to the top>>

=== Not correctly using curly braces and brackets in JSON examples (RAML 1.0)
// APIMF-849

There are many ways to misuse curly braces and brackets. This snippet illustrates one of them. An array of groups of JSON key/value pairs is improperly enclosed in a pair of curly braces.

----
#%RAML 1.0
title: ExampleRAML
...
/rooms:
  displayName: rooms
  get:
    description: get all rooms
    responses:
      200:
        body:
          application/json:
            example: |
             {
               [{
                "Name": "Superior King",
                "Number": "201",
                "Property": "SE030",
                "Status": "Clean"
                },
                {
                "Name": "Junior Suite",
                "Number": "202",
                "Property": "NO131",
                "Status": "Clean"
                }]
              }
----

If the example was meant be an object, then a key must be specified for it.

----
#%RAML 1.0
title: ExampleRAML
...
/rooms:
  displayName: rooms
  get:
    description: get all rooms
    responses:
      200:
        body:
          application/json:
            example:
            {
    	      "some_key": [
                {
                  "Name": "Superior King",
          	  "Number": "201",
          	  "Property": "SE030",
          	  "Status": "Clean"
          	},
          	{
          	  "Name": "Junior Suite",
          	  "Number": "202",
          	  "Property": "NO131",
          	  "Status": "Clean"
          	}
              ]
            }
----

If the example was meant be an array, then the outside curly braces must be removed.

----
#%RAML 1.0
title: ExampleRAML
...
/rooms:
  displayName: rooms
  get:
    description: get all rooms
    responses:
      200:
        body:
          application/json:
            example:
            [
                {
                  "Name": "Superior King",
          	  "Number": "201",
          	  "Property": "SE030",
          	  "Status": "Clean"
          	},
          	{
          	  "Name": "Junior Suite",
          	  "Number": "202",
          	  "Property": "NO131",
          	  "Status": "Clean"
          	}
            ]
----

<<Back to the top>>

=== Problems with named examples (RAML 1.0)
// APIMF-907

To avoid common problems with referencing a named example with an `!include` tag, follow these two rules:

* In your API specification, use the `examples` facet and only one `!include` tag, as in this example:
+
----
#%RAML 1.0
title: test
types:
 A:
    properties:
       a: string
       b: integer
    examples: !include fragment.raml
----

* In the NamedExample fragment, ensure that there is only one entry, and that the entry consists of a name and a value, as in this example:
+
----
#%RAML 1.0 NamedExample
Name:
    a: "b"
    b: 1
----

If you do not follow these rules, you will see the warning messages that are described in the next three sections.

==== Not using the "examples" facet when referencing to a named example

If you see this warning message in the API editor, then your API specification is incorrectly referencing a named example by using an `example` facet:

----
Named example fragments should be included in 'examples' facet
----

You must use an `examples` (`example` with an `s`) facet. For example, the following reference to `fragment.raml` generates the warning message:

----
#%RAML 1.0
title: test
types:
  A:
     properties:
        a: string
        b: integer
     example: !include fragment.raml
----

The resolution is merely to add an `s` to the end of the name of the `example` facet:

----
#%RAML 1.0
title: test
types:
  A:
     properties:
        a: string
        b: integer
     examples: !include fragment.raml
----



==== Not naming named examples

When a named example does not have a name, the editor returns this warning message:

----
Invalid fragment body in [[root.location]] , external fragment will be created
----

[NOTE]
====
This is the same warning message that appears when there is more than one example in a NamedExample fragment. See the next section for examples of that problem.
====

The second line in a NamedExample fragment must be a key that is the name given to the example, as in this snippet:

----
#%RAML 1.0 NamedExample
MyExampleName:
----

The properties of the example then follow after. For example, suppose an API specification defines the following object:

----
user_name:
    type: object
    properties:
        user: string
----

The NamedExample fragment would need to look like this:

----
#%RAML 1.0 NamedExample
MyExampleName:
    user: Lionel
----

Suppose that instead the fragment looked like this:

----
#%RAML 1.0 NamedExample
user: Lionel
----

In this case, `user` is incorrectly parsed as the name and `Lionel` is incorrectly parsed as the example.

To look at another example, suppose that an API specification defined a more complex object:

----
user_name:
    type: object
    properties:
        user:
            name: string
            lastName: string
----

The named example would need to look like this, again with the name of the example immediately following the fragment's declaration:

----
#%RAML 1.0 NamedExample
MyExampleName:
    user:
        name: Lionel
        lastName: Ma
----

Suppose that instead the named example looked like this:

----
#%RAML 1.0 NamedExample
user:
    name: Lionel
    lastName: Ma
----

The editor would not return the warning message in this case. Instead, it would assume that `user` was the name of the example and that the object had two properties, not one complex property.

Here is another case in which the editor would not return the warning message. If a data type includes a `value` facet and your NamedExample for the type does not include the type's name, the editor assumes that `value` is the name of the type, as in this example:

----
#%RAML 1.0 NamedExample
value:
   a: "b"
   b: 1
----

The editor does not issue a warning message and interprets `value` as the name of the example. However, it is better for you to include the name of the example, so that nobody reading through your API specification and related files gets confused about the type that the example is for.

----
#%RAML 1.0 NamedExample
Name:
  value:
      a: "b"
      b: 1
----



==== Including more than one named example in a single NamedExample fragment

A NamedExample fragment can contain only one example. The following fragment would generate a warning:

----
#%RAML 1.0 NamedExample
Name1:
   a: "b"
   b: 1

Name2:
    a: "h"
    b: 5
----

This is the warning message that you will see:

----
Invalid fragment body in [[root.location]] , external fragment will be created
----

[NOTE]
====
This is the same warning message that appears when the example in a NamedExample fragment is missing a name. See the previous section for examples of that problem.
====

To resolve the problem, you would need to use only one of the examples:
----
#%RAML 1.0 NamedExample
Name1:
   a: "b"
   b: 1
----

A single type declaration in an API specification can use only one `!include` tag in an `examples` facet. Therefore, you cannot split the NamedExample fragment into two NamedExample fragments and use both named examples.

In this next example, there are two properties in a single example. However, the warning message appears because `a` and `b` are parsed as two examples.

----
#%RAML 1.0 NamedExample
  a: "b"
  b: 1
----

If you add the name of the type, then the warning message no longer appears because the parser correctly interprets the two properties as belonging to a single named example:

----
#%RAML 1.0 NamedExample
Name:
  a: "b"
  b: 1
----


// === Common Error 4
// APIMF-966
// *_Not using a correct value for the `protocols` node_*
//
// The value of the `protocols` node must be an array. The array must be:
//
// * `[http]` or `[HTTP]`
// * `[https]` or `[HTTPS]`
// * `[http, https]` or `[HTTP, HTTPS]`

<<Back to the top>>

=== Including an example response that contains invalid JSON (RAML 1.0)
// APIMF-967

When a JSON file is included as the example of a response message, the JSON in the file must be valid. In this example of the error, the example of the response for the 200 response code contains an `!include` statement. The JSON in the included file incorrectly contains a comma after the last key/value pair.

----
#%RAML 1.0
title: ExampleRAML
...
/resume:
  description: "Gets candidate's resume."
  get:
    queryParameters:
       ...
    headers:
      ...
    responses:
      200:
        body:
          application/json:
            example: !include exampleResumeData-200.json
      500:
        ...
----


----
{
...
"assesments.characteristic.focusofattention.data"= "",
}


----

<<Back to the top>>

=== Referencing libraries by using the `type` key (RAML 1.0)
// APIMF-1030

As explained in the RAML 1.0 specification, you must apply libraries with the `uses` node:

____
Any number of libraries can be applied by using the OPTIONAL uses node ONLY at the root of a ["master"] RAML or RAML fragment file. The value of the uses node is a map of key-value pairs. The keys are treated as library names, or namespaces, and the value MUST be the location of a RAML library file, usually an external RAML library fragment document.
____

Therefore, the following snippet is incorrect, given that the file `financeDetail.raml` is a library.

----
#%RAML 1.0
title: ExampleRAML
...
/claims:
  /{claim-id}:
    patch:
      body:
        application/json:
          type: !include financeDetail.raml
----

This next snippet is correct.

----
#%RAML 1.0
title: ExampleRAML
uses:
  lib: financeDetail.raml
/claims:
  /{claim-id}:
    patch:
      body:
        application/json:
          type: lib.myType
----

<<Back to the top>>

=== Specifying values for an enum that does not match the enum's data type (RAML 1.0)
// APIMF-1062

Because of the editor's strict parsing according to the YAML specification, it does not automatically cast values to declared data types. To illustrate the error, here is an invalid declaration of an enum:

----
type: string
enum: [1,2,3]
----

The data type for the enum is `string`; however, the values are all integers. Because the editor stricly parses according to the YAML specification, it does not cast the integers to `string` values automatically. Therefore, either the type is declared incorrectly in this example and should be `integer`, or the enum values need to be in quotation marks.

Here is another invalid declaration:

----
type: string
enum: [
        "a",
        "b",
        "c",
        false,
        3.0
      ]
----

The value `false` is a `boolean`, while the value `3.0` is a `float`. Neither is converted to a `string` value by the editor.

The next three declarations are valid.
----
type: string
enum: ["1","2","3"]
----

----
type: integer
enum: [1,2,3]
----

----
type: string
enum: [
        "a",
        "b",
        "c",
        "false",
        "3.0"
      ]
----

[NOTE]
====
This error can occur not just in enums, but also anywhere an `integer`, `nil` value, or value of some other data type is introduced where the parser expects a `string` value.
====

<<Back to the top>>

=== Using, in an example of a numeric type, an incorrect format for that type, if a format is specified (RAML 1.0)
// APIMF-1070

Examples of numeric types must conform to restrictions specified in the `format` node. In this example of the error, the format specified for the numeric type `collection` is int8. However, the value of the example is greater than 127.

----
#%RAML 1.0
title: ExampleRAML
...
types:
  collection:
    type: integer
    format: int8

/search:
  /code:
      get:
       body:
        type: collection
        example: 22342342
----

<<Back to the top>>

=== Not defining a media type for an empty body when no default media type is defined (RAML 1.0)
// APIMF-1158

It is possible to specify media types globally for an entire API specification or locally for individual `body` nodes. According to the RAML 1.0 specification, a global definition looks like this:

----
#%RAML 1.0
title: New API
mediaType: application/json
----

This example, also from the RAML 1.0 specification, uses both a global and a local definition. In this case, the `mediaType` node defines acceptable media types as `application/json` and `application/xml`. The first type, `Person`, returns a body that is in either media type. However, the second type, `Another`, overrides the global definition with a local one, and returns only a JSON body.

----
#%RAML 1.0
title: New API
mediaType: [ application/json, application/xml ]
types:
  Person:
  Another:
/list:
  get:
    responses:
      200:
        body: Person[]
/send:
  post:
    body:
      application/json:
        type: Another
----

The common error is demonstrated in both of these two following examples. There is no `mediaType` node in either example that defines the media types globally. Moreover, neither of the `body` nodes defines its media type. If there is no global definition, an empty body must use a local definition.

----
#%RAML 1.0

title: ExampleRAML

/endpoint:
  get:
    body:
    responses:
      200:
----

----
#%RAML 1.0

title: ExampleRAML

/endpoint:
  get:
    responses:
      200:
        body:
----

<<Back to the top>>
