= GitHub Synchronization

API specification designers often use multiple authoring and version control tools. This can result in maintaining several different specification versions. 

GitHub Synchronization is a version control tool that maintains API specifications existing in several locations. Use GitHub Synchronization to enable two-way synchronization between API Designer and your GitHub repository and to automatically capture changes to API projects and send the changes to a synchronized GitHub repository of your choice. Similarly, the application automatically propagates to your API project any changes made in a synchronized GitHub repository.

This bidirectional flow extends API Designer into a collaborative environment where the single source of truth is always GitHub. Unlimited collaborators can share and contribute to the same content.

Using GitHub synchronization with API Designer enables you to:

* Create new GitHub repositories that synchronize with existing API projects.
* Create new API projects that synchronize with new GitHub repositories.
* Create new API projects that synchronize with existing remote GitHub repositories.

To perform GitHub-specific actions, such as opening pull requests, viewing branch diffs, or viewing synchronization status, use the GitHub UI. 

== See Also

* xref:design-ghs-install-authorize.adoc[Install and Authorize GitHub Synchronization]
* xref:design-ghs-new-project-new-repo.adoc[Create a New Project Synchronized with a New GitHub Repository]
* xref:design-ghs-new-project-existing-repo.adoc[Create a New Project Synchronized From an Existing GitHub Repository]
* xref:design-ghs-new-repo-existing-project.adoc[Create a New GitHub Repository Synchronized from an Existing Project]


