= The Table of Contents
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images

The table of contents that appears can contain several sections when you select the main file in a RAML API-specification project or the file in an OAS project:

* *Summary*: Click this to go to the summary page of the specification.
* *Endpoints*: Expand this section to see a list of all of the endpoints that are defined in the specification. Expand an endpoint to see links to the endpoint's overview page and the documentation of the endpoint's methods.
* *Types*: Expand this section to a list of all of the types that are defined in the specification. Click a type to open its documentation.
* *Security*: Expand this section to see a list of the security schemes that are defined in the specification. Click a scheme to open its documentation.
// We render for 4 of 7 fragment types: libraries (Types in the TOC), security schemes (Security in the TOC), documentation (Documentation in the TOC, with each entry being a title/content pair), and types (Types in the TOC).
