= Fork a Project in the RAML Editor
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You can separate new iterations of a project from previous iterations by branching.

== About this task

A new branch is a fork of your project and cannot be merged back into the master branch. Anybody who has access to your project can also create branches.

Even when there are forks of a project, when you open that project the editor opens it to the master branch. If you want to return to a fork that you were working in, you must select that fork.

You can publish any fork of an API specification to Anypoint Exchange.

== Procedure

* To fork a project:
+
. Open the project.
. Click “master” at the top of the API editor.
. Type a name in the search field and type *Enter*.
+
*Result:* The API editor automatically switches to the new fork.

* To work in a fork of a project:
+
. Open the project.
. Click “master” at the top of the API editor.
. Select the name of the fork that you want to work in.