= Correcting Common Errors in Conforming to RAML 0.8

When testing the new parser, MuleSoft identified ten common errors in API specifications written in RAML 0.8.

== Common Error 1
*_Validation fails for an example of a Boolean enum_*

If the values for a Boolean enum are either both strings or both Boolean values, the example of the enum must be a string.
[source,json]
----
#%RAML 0.8
title: PSN
version: v0.1
/psn:
  head:
    responses:
      204:
        headers:
          X-PSN-Exists:
            enum: [true, false]
            example: "true"
----

[source,json]
----
#%RAML 0.8
title: PSN
version: v0.1
/psn:
  head:
    responses:
      204:
        headers:
          X-PSN-Exists:
            enum: ["true", "false"]
            example: "true"
----

== Common Error 2
*_JSON files that are included as schemas must be valid_*

In this example, appSwitcher.json must contain valid JSON.
[source,json]
----
#%RAML 0.8
title: myApp
version: v1
securitySchemes:
  - oauth_2_0: !include securitySchemes/oauth_2_0.raml
  - tokenSchema: !include securitySchemes/tokenSchema.raml
schemas:
  - appSwitscher: !include schemas/appSwitscher.json
----

== Common Error 3

*_An example of an integer type must also be an integer_*

[source,json]
----
#%RAML 0.8
title: Mobile Experience API
version: 1

/products:
  /product/{product_id}:
    description: Get product instance details
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "$schema": "http://json-schema.org/draft-03/schema",
                  "id": "http://jsonschema.net",
                  "properties": {
                      "unit_price": {
                          "type": "integer"
                      }
                  }
                }
              example: |
                {
                  "unit_price": 19.00
                }
----

[source,json]
----
#%RAML 0.8
title: Order Entry API
/orders:
  /{id}:
    uriParameters:
      id:
        type: integer
        example: "451"
----

== Common Error 4
*_An example of a schema that defines a required property must use that property_*

[source,json]
----
#%RAML 0.8
title: SFOrdersAPI
/order:
  /{id}:
    get:
      responses:
        200:
          body:
            application/json:
              schema: |
                {
                  "type":"object",
                  "$schema": "http://json-schema.org/draft-03/schema",
                  "id": "http://com.mulesoft.demo.orders.get.json.order",
                  "properties":{
                      "property": {
                        "type":"string",
                        "id": "http://com.mulesoft.demo.orders.create.json.get.sfOrderId",
                        "required":true
                      }
                  }
                }
              example: |
                {
                  "anotherProp": 14523
                }
----

[source,json]
----
{
  "orderId": 14523,
  "sOrderId": "fadfead3524523",
  "sfAccountId": "fedfes3653635",
  "orderName": "Order From Someone",
  "total": 174.92,
  "orderType": "E-Commerce Order",
  "description": "A good order description",
  "orderDate": "04-03-1980"
}
----

== Common Error 5
*_If a schema defines a data type that is an object, an example of that schema must also use an object_*

[source,json]
----
#%RAML 0.8
title: Muse API
version: 1.0.0
schemas:
  - presentation: |
      {  "$schema": "http://json-schema.org/draft-03/schema",
         "type": "object",
         "properties": {
           "title":  { "type": "string" }
         }
      }
resourceTypes:
  - base:
      get?:
        responses: &standardResponses
          200:
            description: OK
  - typedCollection:
      type: base
      get:
        responses:
          200:
            body:
              application/json:
                schema: <<schema>>


/presentations: &presentations
  type: { typedCollection: { schema: presentation } }
  get:
    responses:
      200:
       body:
         application/json:
           example: |
             [
              {
                  "title": "Presentation Video"
              },
              {
                  "title": "Environment Spec Report"
              }
              ]

----

----
Content is not valid according to schema: Expected type object but found type array at (36, 14)
----

== Common Error 6
*_An example for a boolean property must have a value of "true" or "false"_*

[source,json]
----
#%RAML 0.8
title: Photo-posting API

/upload:
  post:
    description: |
      Upload a photo
    body:
      multipart/form-data:
        formParameters:
          title:
            description: The title of the photo.
          is_public:
            type: boolean
            example: 1
----

== Common Error 7
*_Paths for included files must be relative_*

The path "/common/common_400.example" is an absolute path, relative to the root RAML file location. To be a relative path it must be "./common/common_400.example" or "common/common_400.example".

./api.raml
[source,json]
----
#%RAML 0.8
title: Global Status API
traits: !include ./common/traits.raml

/booking/list:
    is: [common_errors]
    post:
        body:
            application/json:
                example: {}
----

./common/traits.raml
[source,json]
----
- common_errors:
    responses:
      400:
        body:
          application/json:
            example: !include /common/common_400.example
----

./common/common_400.example
[source,json]
----
{
  "status": 400,
  "code": "USR",
  "message": "Invalid email address",
  "transaction_id": "ABC123"
}
----

== Common Error 8
*_Examples of JSON schemas must be valid_*

[source,json]
----
#%RAML 0.8
title: test

/api:
  get:
    responses:
      200:
        body:
          application/json:
            schema:
              {
                "type": "object",
                "required": true,
                "$schema": "http://json-schema.org/draft-03/schema",
                "properties": {
                  "a": {
                    "type": "boolean",
                    "required": true
                  }
                }
              }
#              Invalid json
            example:
              {
                "a: {
                  "a": ""
                }
----


== Common Error 9
*_The title node cannot lack a value_*

[source,json]
----
#%RAML 0.8
title:
----

== Common Error 10
*_If the type for a query parameter is string, then the example for the query parameter must also be string_*

[source,json]
----
#%RAML 0.8
title: HsbcBankingRaml
/books:
  get:
    queryParameters:
      publicationYear:
        type: string
        example: 2016
----
