= Modify Published RAML API Specifications to Conform Completely to RAML 0.8 or 1.0

[[bookmark-a,Back to the top]]

As of January 10, 2019, the API editor (one of the two editors in Design Center's API Designer) uses stricter validation for specifications that are written in RAML. Therefore, it is possible that one or more of the APIs that you used previous versions of the API editor to create include invalid RAML that those previous versions did not flag.

Check your published APIs by opening them in the API editor in Design Center. You can use this guide to correct a number of common RAML problems that were validated by the API editor in the past. If you see problems that this guide does not include, refer to the specifications for RAML 0.8 and 1.0, which you can read on https://raml.org/[raml.org].

In addition to checking more precisely for RAML problems, the API editor also validates regular expressions. Any invalid expressions in published API specifications that you reopen in the editor are now flagged as errors.

You have a long grace period to correct any invalid RAML and invalid regular expressions that your published API specifications might include. After the grace period expires, you will be unable to republish and redeploy API specifications in which such problems still exist.

[IMPORTANT]
====
You do not need to check any API specifications that were created with the visual API editor, the tool in API Designer with which you can create specifications by filling in forms.
====

* xref:design-common-problems-raml-08.adoc[Common Problems in Conforming to RAML 0.8]
* xref:design-common-problems-raml-10.adoc[Common Problems in Conforming to RAML 1.0]
* xref:design-common-problems-raml-08-10.adoc[Common Problems in Conforming Either to RAML 0.8 or 1.0]
