= Modify Published RAML API Specifications to Conform Completely to RAML 0.8 or 1.0

[[bookmark-a,Back to the top]]

Soon, the API editor in Design Center will be more precise in ensuring that the RAML in your API specifications is valid. However, it will be possible that one or more of the APIs that you used previous versions of the API editor to create and publish to Anypoint Exchange will include invalid RAML that those previous versions did not flag.

== Fixing Invalid RAML in Your API Specifications

You will need to check your published APIs by opening them in the API editor in Design Center. You can use the following guides to correct a number of common errors that MuleSoft has found while testing the changes to the API editor on a large number of RAML API specifications.

* xref:design-common-errors-raml-08.adoc[Common Errors Found in RAML 0.8 API Specifications]
* xref:design-common-errors-raml-10.adoc[Common Errors Found in RAML 1.0 API Specifications]

If, after the changes to the API editor are released, you see errors that this guide does not include, refer to the specifications for RAML 0.8 and 1.0, which you can read on https://raml.org/[raml.org].

== How the Changes Affect the Use of Your Published RAML API Specifications in Studio and Mule Runtime

You will have a long grace period to correct any invalid RAML that your published API specifications might include. The grace period will start on the date that the changes to the API editor are released. See xref::design-scenarios-for-published-apis.adoc[How the Changes to the API Editor Affect the Use of Published RAML API Specifications] to learn how RAML API specifications that you correct in the API editor before or after the grace period ends.
