= Switch Connection in a Project
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

:imagesdir: ../assets/images

Every connector that you include in a flow in a Mule-app project is configured to use a connection to connect at runtime to the system that the connector is for. A _connection_ is a saved set of information that a running Mule app must use to connect to a specific system by means of a connector. For example, you configure a Salesforce connector to use a specific connection to Salesforce, a Database connector to use a specific connection to a database.

You can change a configuration to use a different connection or you can create and use a configuration that uses a different connection.

For example, suppose that you add a Database connector to a flow. When you create the configuration for it, you create Connection A to specify the information that the your Mule app needs to connect to a MySQL database at runtime. Now, you want to test your Mule app against an Oracle database.
