= Edit a Connection
:page-support-status: eolReached 
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

:imagesdir: ../assets/images

You can edit a connection that is being used by or is available to be used by a specific type of connector.

To edit a connection, you must log into Anypoint Platform with the user ID that was used to create the connection. You cannot edit a connection that was created under a user ID that you are not logged in with.

If the connection is shared, the changes affect all of the connectors of that type in all of the projects in your business group.

*To edit a connection:*

. Open a Mule-app project that includes a connector of the type that can use the connection.
. Click the card that represents the connector type.
. At the top of the card, click *Edit*.
. Locate the connection in the list of available connections.
. Click the three dots to the right of the connection's name and click *Edit*.
. Make your changes.
. Click *Save*.
. Click *Cancel* or *Save* to close the configuration dialog for the connector.
+
It doesn't matter which button you click. The changes to the connection are saved when you click *Save* in the previous dialog.

== See Also

* xref:fd-connections.adoc[Connections from Connectors to Systems]
* xref:connectors::index.adoc[Connectors and Modules (for Mule 4)]
