= Deploy a Mule Application from Runtime Manager

Perhaps your organization requires someone with the proper authority to deploy Mule applications once the design phase has been completed.
Flow Designer allows you to export the project as a `.jar` file and share it with those who are responsible for Mule app deployment.
You'll need to use *Export mule application*, as it produces a .jar file that includes all the connector credentials and artifacts required by the Mule runtime.

. In Flow Designer, ensure that your project is free of errors.
. Export your project by clicking the dots next to the Test button and select *Export* from the list.
. Select *Export mule application* for the entire app, and click *Export*.
+
A `.jar` file containing a copy of your Mule app downloads to the default location on your computer.

. Place the `.jar` file in a location that the other person can access.
. Have the person receiving the `.jar` file follow these steps in Runtime Manager:
.. Switch to the environment in which the Mule application is to be deployed.
.. Click *Deploy Application*.
+
 The Deploy Application page is opened.

.. Select *Choose File* > *Upload File* and upload the `.jar` file.

.. Follow the instructions in xref:runtime-manager::deploying-to-cloudhub.adoc[Deploying to CloudHub].

== See Also

* xref:access-management::environments.adoc[Environments]

* xref:runtime-manager::managing-deployed-applications.adoc[Manage Deployed Applications]

* https://help.mulesoft.com[MuleSoft Help Center]
