= Deploy a Mule Application from Runtime Manager

It might be the case that you are not allowed to deploy an application directly from Flow Designer.
Your organization might require someone with the proper authority to deploy applications from Runtime Manager.
You can share with that person a copy of your project source files or the entire Mule app as a `.jar` file.
Using *Export project sources* exports just your project source files, while *Export mule application* exports the entire Mule app.


In Flow Designer, follow these steps:
.. Ensure that your project is free of errors.
.. Export your project by clicking the dots next to the Test button and select *Export*.
.. Select *Export project sources*, or *Export mule application* depending on your needs, and then click *Export*.
+
 A `.jar` file that contains a copy of your project source or Mule app with your credentials is downloaded to the default location on your computer.

. Place the `.jar` file in a location that the other person can access.
. Have the person receiving the `.jar` file follow these steps in Runtime Manager:
.. Switch to the environment in which the Mule application is to be deployed.
.. Click *Deploy Application*.
+
 The Deploy Application page is opened.
.. Select *Choose File* > *Upload File* and upload the `.jar` file.
.. Follow the instructions in xref:runtime-manager::deploying-to-cloudhub.adoc[Deploying to CloudHub].

== See Also

* xref:access-management::environments.adoc[CloudHub Environments]
* xref:runtime-manager::managing-deployed-applications.adoc[Manage Deployed Applications]
