= The Elements of Flows in Mule Applications (Flow Designer)
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

The cards in a flow each represent a core component, an operation of a connector, a module, or an API.

Core components:: You can use them to add logic to your flows and perform some tasks. Here is a sampling of the features that core components offer:

* Initiating subflows
* Logging
* Setting payloads
* Transforming data
* Creating Try scopes in your flows so that you can catch and respond to errors

+
For example, the Choice router is a component that dynamically routes messages through a flow according to a set of DataWeave expressions that evaluate message content. Each expression is associated with a different routing option. The effect is to add conditional processing to a flow, similar to an if/then/else code block in most programming languages.

Connectors:: You can use connectors to allow your apps to connect to SaaS and on-premises applications, systems, and services.

* The Salesforce connector lets your application perform a large number of operations in Salesforce.
* The Database connector lets your application perform operations in your databases.
* The HTTP connector lets your application receive HTTP requests and send HTTP responses.

Modules:: Modules group together operations that were created to add flexibility to your applications. They let applications aggregate values compress data, use Java features, use extra features for processing JSON, and more. The features that modules offer are more at the level of traditional application coding.
+
For example, the XML module provides components that can process and extract data from an XML document.

APIs:: When someone in your Anypoint-Platform organization publishes an API specification to Exchange from API Designer, Exchange creates a REST API that is based on that specification. That API is available to use in applications that are created in your organization.

== See also

* xref::fd-tour.adoc[Tour of Flow Designer]
* xref:connectors::index.adoc[Connectors and Modules (for Mule 4)]
