= Share a Mule Application as a Template on Exchange

You can publish a Mule application as a template on Exchange, which makes it easy for you and other people to create similar Mule applications in the future.

== About this task

Publishing Mule applications as templates is a great way to share your work with other people. When they need to build a similar application, they can get a head start by downloading and using your template to start their own project. You might even find in the future that you need to create Mule applications that are similar to one that you've already created.

You might have figured out that it would be possible for you and other people in your organization simply to clone a project that you have created, and to start a new Mule application from that cloned project, rather than use a template. However, those other people would need to know the name of your project. The benefit of publishing a template is that they could search Exchange for a template that suits their needs and read descriptions for each template that appears in their search results. A Mule-application project might be harder to find and a project does not let you provide a description of a Mule application or explain how to use it.

== Before you begin

* Ensure that your Mule application is free of errors.

* Ensure that your user ID has permission to publish to Exchange in your Anypoint Platform organization. An administrator in your organization can grant you this permission by assigning your user ID the role of Exchange Contributor, Exchange Admin, or Organization Administrator.

* Ensure that you have written notes in the *Notes* section of each card to explain the purpose of the card and any information that someone might need to configure the card.

* Open the project in which you created the Mule application.


== Procedure

. Click the *Publish* button, which is in the top-right corner of the Flow Designer screen.
. Specify a name for the template.
. Click *Publish*.

== Result

You can view the new page in Exchange that has been created for your template.

If Flow Designer was unable to publish the template, check that your user ID has permission to publish to Exchange.

== What to do next

On the template's page in Exchange, provide a description, screeshots, or videos to explain the purpose of the template and how to use it.
