= Collaborate with Someone who Works in Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

:imagesdir: ../assets/images

When designing your Mule application, you might want help from someone else in your Anypoint-Platform organization,
such as a developer, who works in Anypoint Studio.
You must first use Flow Designer to export the project as a `.jar` file, to share it with someone with developer credentials so that they can import it into Anypoint Studio. Ensure that the project is free of errors.

To do so, you use *Export project sources* to share just the source files (including all the connector credentials),
without all of the other Mule artifacts.

As the other person works on the project, they can take advantage of the advanced features of Studio.
When they are finished, they can deploy the project from Studio.

. Export your project by clicking the dots next to the Test button and select *Export* from the list.
+
You see a pop-up with export choices.
+
. Select *Export project sources* to share just your project source files, and click *Export*.
+
A `.jar` file containing a copy of your Mule app downloads to the default location on your computer.
+
. Alert the recipient who works in Studio that the `.jar` is available so that they can:
.. Access the `.jar` file and place it in a location where they can easily upload it from Studio.
.. Enable Studio to access your organization in Anypoint Platform by selecting *Preferences* > *Anypoint Studio* > *Authentication*.
.. Import the `.jar` file by selecting *File* > *Import* and then selecting *Anypoint Studio* > *Packaged Mule Application (.jar)*.
+
Studio opens the project.

== What To Do Next

JAR files exported from Flow Designer contain a file named mule-config.xml and a file named mule-artifact.properties.

The file mule-config.xml contains placeholders for information that connectors in the exported app need to use to make connections to systems.

For example, for a Salesforce connector that uses a password, security token, and username, the entry in mule-config.xml that contains the connection information looks like this:

----
<salesforce:cached-basic-connection password="<password>"
                                    securityToken="<token>"
                                    username="<username>"/>
----

The placeholders that FD will replace the values with are these:
----
salesforce.connection.password 
salesforce.connection.securityToken 
salesforce.connection.username
----

Not only with the placeholders be in mule-config.xml, but they will be listed in mule-artifact.properties, which is also in each exported JAR file.

You can look in mule-artifact properties to see what connectivity info was removed for each connector. After you obtain that info, you can edit mule-config.xml to replace the placeholders with the info. Then, you compress the folders as a JAR file again.

== See Also

* xref:fd-troubleshooting.adoc[Troubleshooting in Flow Designer]
* https://help.mulesoft.com[MuleSoft Help Center]
