= Collaborate with Someone who Works in Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

:imagesdir: ../assets/images

When designing your Mule application, you might want help from someone else in your Anypoint-Platform organization,
such as a developer, who works in Anypoint Studio.
You must first use Flow Designer to export the project as a JAR file, to share it with someone with developer credentials so that they can import it into Anypoint Studio. Ensure that the project is free of errors.

To do so, you use *Export project sources* to share just the source files (including all the connector credentials),
without all of the other Mule artifacts.

As the other person works on the project, they can take advantage of the advanced features of Studio.
When they are finished, they can deploy the project from Studio.

. Export your project by clicking the dots next to the Test button and select *Export* from the list.
+
You see a pop-up with export choices.
+
. Select *Export project sources* to share just your project source files, and click *Export*.
+
A JAR file containing a copy of your Mule app downloads to the default location on your computer.
+
. Alert the recipient who works in Studio that the JAR is available so that they can:
.. Access the JAR file and place it in a location where they can easily upload it from Studio.
.. Enable Studio to access your organization in Anypoint Platform by selecting *Preferences* > *Anypoint Studio* > *Authentication*.
.. Import the JAR file into Studio by selecting *File* > *Import* and then selecting *Anypoint Studio* > *Packaged Mule Application (.jar)*.
+
Studio opens the project.

== What To Do Next

No sensitive connection information, such as usernames, passwords, and security tokens, is included in the exported
JAR file. Therefore, you must provide that information for every connector in the app after you import the JAR file into Studio as a project. You do that in the `src/main/resources/mule-artifact.properties` file in the project.

For example, suppose that an instance of Salesforce Connector in an app uses a configuration that includes a *Basic Username Password* connection. For this type of connection, you must provide a username, password, and a security token. The username, password, and security token that are in the configuration that the connector uses when the app is in Flow Designer are not included in the configuration in the exported JAR file. After you import the JAR file into Studio as a project, you see the file `src/main/resources/mule-artifact.properties` in the file tree for the project. Double-click that file to open it in an editor in Studio. In it are keys for the connection information for every configuration that is being used by a connector in the app. For the *Basic Username Password* connection in the configuration that the instance of Salesforce Connector is using, these are the three keys:

----
salesforce.connection.password =
salesforce.connection.securityToken =
salesforce.connection.username=
----

The names of all keys for connection information contain three parts, the middle part being `connection`. You must provide values for all of these keys in the file. After saving the file, you can test and run the app.

== See Also

* xref:fd-troubleshooting.adoc[Troubleshooting in Flow Designer]
* https://help.mulesoft.com[MuleSoft Help Center]
