= Simple Data Types that are Supported in Flow Designer

These data types are called simple because, though they store data in particular formats, they have no structures, such as custom data types do. The simple data types are boolean, date, dateTime, integer, number, and string.

Boolean:: Evaluates to true or false. Possible values: `true`, `false`

Date:: Stores a year, month, and day as `yyyy-MM-dd`.

DateTime:: Stores a date and time within a time zone, where a time zone is the time relative to Greenwich Mean Time (GMT). A time zone must include a + or a -. For example, `03:00:00` is a time, while `+03:00` is a time zone. Example that represents 12:30 p.m. on June 1, 2019 in Macau: `2019-06-01T12:30:00+08:00`

Integer:: Stores whole numbers that range from -2,147,483,647 to 2,147,483,647. An integer has no decimal point.

Number:: A `number` stores a float number, which can range from 1.40129846432481707e-45 to 3.40282346638528860e+38 and include a decimal point, or an integer.

String:: Stores text, numbers (not `number` data types), or a combination of both. Examples: "94u0sfjlk*(f!`lkkjd", "18005555555", "Fred"

== See also

* xref:about-data-types.adoc[Define and Use Data Types in a Flow]
* xref:fd-custom-data-types.adoc[Custom Data Types in Flow Designer]
