= Collaborate with Someone who Works in Studio
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:

:imagesdir: ../assets/images

When you are creating a Mule application, there might come a time when you would like help from someone in your Anypoint-Platform organization, such as a developer, who works in Studio. You can download your project as a `.jar` file and then place that file in a location from which the other person can import it into Studio.

As the other person works on the project, the changes are applied to your project online in Flow Designer. When the other person is finished, you can open your project in Flow Designer and pick up where that person left off.

== Procedure

. In Flow Designer, follow these steps:
.. Ensure that your project is free of errors.
.. Click the download icon, which is to the right of the Undo and Redo arrows in the top-left corner of the screen.
.. Select *Download Source*.
+
*Result:* A `.jar` file that contains a copy of your project is downloaded to the default location on your computer.
. Have the person who works in Studio follow these steps:
.. Enable Studio to access your organization in Anypoint Platform by selecting *Preferences* > *Anypoint Studio* > *Authentication* and entering your user ID and password for Anypoint Platform.
.. Import the `.jar` file by selecting *File* > *Import* and then selecting *Anypoint Studio* > *Packaged Mule Application (.jar)*.
+
*Result:* Studio opens the project.

== What To Do Next

The person who works in Studio can work on the project. All changes are made automatically to the project in Design Center. When the work in Studio is completed, ensure that the project is deleted from Studio. If you need help again later, repeat the procedure to share your project.

== See Also

* xref:fd-troubleshooting.adoc[Troubleshooting in Flow Designer]
