= Import a Mule Application

ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

:imagesdir: ../assets/images


You can import a Mule-application project that was exported from Design Center. This feature supports two different scenarios:

* Importing a project that was exported from a different environment within a single organization
* Importing a project that was exported from an environment that is in a different organization

////

* If you plan to import a Mule application that was exported from Anypoint Studio, ensure that, when it was exported, these options were selected:
** In the Export dialog: *Mule* > *Anypoint Studio Project to Mule Deployable Archive (includes Studio metadata)*
** In the Export Mule Project dialog:
*** Select *Attach project sources*.
*** Select *Only export project sources*.
* Studio supports all of the core components that come with Mule Runtime, while Design Center supports a subset. If you want to import a project that was exported from Studio, ensure that the project includes core components from the following list only:
** Choice
** Flow Reference
** For Each
** Logger
** Scheduler
** Set Payload
** Set Variable
** Transform
** Try
////

== Procedure

. On the *Projects* page of Design Center, click the *Create* button and then click *Import Application*.
. Specify a name to give to the imported project.
. Browse your filesystem for the `.jar` file that contains the project.
// . Browse your filesystem for the `.jar` file that contains the project. Both Design Center and Studio export Mule-application projects in `.jar` files.
. Click *Import*.

[NOTE]
====
If one or more connectors, components, or modules referenced by the project are custom-developed and not available in your environment, then the import fails with a message like this one:

....
Unable to resolve dependency 2bacbe78-4300-965a-39fce81ee15d:mule-plugin-americanflights:jar:mule-plugin:1.0.0
Where
2bacbe78-4300-965a-39fce81ee15d is the Maven groupI for the artifact
Mule-plugin-americanfligths is the Maven artifact ID
jar is the type of the Maven artifact
mule-plugin is the classifier of the Maven artifact
1.0.0 is the version of the Maven artifact.
....

If you see such an error, ask the owner of the asset xref:exchange::to-publish-assets-maven.adoc[to publish it to Exchange by using Maven].

====
