= About Design Center
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:
:page-aliases: user-access-to-design-center.adoc, about-designing-a-mule-application.adoc, fd-tour.adoc, salesforce-to-twilio.adoc, fd-elements-of-flows.adoc, import-template.adoc, to-create-a-mule-application-project.adoc, fd-connections.adoc, fd-connection-create.adoc, fd-connection-switch-in-project.adoc, fd-connection-edit.adoc, fd-connection-delete.adoc, fd-connection-view-audit-logs.adoc, about-data-types.adoc, fd-supported-simple-data-types.adoc, fd-custom-data-types.adoc, fd-integrating-systems.adoc, dynamic-expression-field.adoc, custom-expression-field.adoc, fd-add-core-component.adoc, fd-iterating.adoc, fd-scatter-gather.adoc, reference-flow-task-design-center.adoc, error-handling-task-design-center.adoc, fd-transform.adoc, fd-mapping-examples.adoc, fd-tour-transform-card.adoc, get-mapping-recommendations.adoc, fd-store-data-top.adoc, to-create-and-populate-a-variable.adoc, fd-store-reuse-output.adoc, manage-dependency-versions-design-center.adoc, fd-share-to-studio.adoc, jump-runtime-manager-task.adoc, fd-project-history.adoc, fd-troubleshooting.adoc, logger-task-design-center.adoc, troubleshooting-reference.adoc, viewing-problems-fd-canvas.adoc, view-clear-logs-task.adoc, fd-deploy.adoc, promote-app-prod-env-design-center.adoc, fd-deploy-app-from-rm.adoc, fd-publish-app-as-template.adoc

Anypoint Design Center is a development environment that includes xref:design-create-publish-api-specs.adoc[API Designer], a tool that enables you to create API specifications in several modeling languages and create RAML API fragments. After you create a specification or fragment, publish it to Anypoint Exchange for anyone in your MuleSoft organization to use.

NOTE: Flow Designer is https://help.mulesoft.com/s/article/MuleSoft-Product-Feature-Retirements[end of life] and its documentation is now located at https://archive.docs.mulesoft.com/design-center/index[Flow Designer archive site].

== Prerequisites for Using Design Center

You must meet the following requirements for accessing Design Center, using its features, running and deploying apps, and publishing designs to Exchange:

* Be assigned the Design Center Developer permission or be the Organization Owner.
* Be assigned the CloudHub Admin role for the Design environment.
* Be assigned the Exchange Contributor role.
* Belong to an Anypoint organization that has at least one CloudHub Design Environment with 0.2 vCores of available capacity.

To deploy to the production environment from Design Center, your user account also needs to be assigned to a CloudHub Developer role specifically for the production environment.

== Where to Start Using Design Center
To start using Design Center, click Design Center after signing into Anypoint Platform. The Projects list appears. See the documentation for API Designer and for Flow Designer for the steps to create projects for those tools.

== See Also

* xref:access-management::roles.adoc[Roles]
* xref:access-management::environments.adoc[CloudHub Environments]
