= About Design Center
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]
:keywords:
:page-aliases: user-access-to-design-center.adoc

Anypoint Design Center is a development environment that consists of two tools:

* xref:design-create-publish-api-specs.adoc[API Designer]
+
API Designer enables you to create API specifications in several modeling languages and create RAML API fragments. To use it, on the *Projects* page in Design center, click *Create New* and select *New API Specification*. After you create a specification or fragment, publish it to Anypoint Exchange so that anyone in your MuleSoft organization can use it.

* xref:about-designing-a-mule-application.adoc[Flow Designer]
+
In Flow Designer, you create Mule applications to integrate systems into workflows. To use it, on the *Projects* page in Design center, click *Create new* and select *New Mule App*.

== Prerequisites for Using Design Center

You must meet the following requirements for accessing Design Center, using its features, running and deploying apps, and publishing designs to Exchange:

* Be assigned the Design Center Developer permission or be the Organization Owner.
* Be assigned the CloudHub Admin role for the Design environment.
* Be assigned the Exchange Contributor role.
* Belong to an Anypoint organization that has at least one CloudHub Design Environment with 0.2 vCores of available capacity.

To deploy to the production environment from Design Center, your user account also needs to be assigned to a CloudHub Developer role specifically for the production environment.

== Where to Start Using Design Center
To start using Design Center, click Design Center after signing into Anypoint Platform. The Projects list appears. See the documentation for API Designer and for Flow Designer for the steps to create projects for those tools.

== See Also

* xref:access-management::roles.adoc[Roles]
* xref:access-management::environments.adoc[CloudHub Environments]
