= API Specification for MuleSoft Connectivity Ecosystem
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

If you are an independent software vendor (ISV), you can participate in the MuleSoft Connectivity Ecosystem by auto-generating a connector from a REST API specification. These steps explain how to prepare your API specification in Anypoint Platform and how to work with your Mulesoft BD counterpart to do the rest.

. In Anypoint Platform, follow these steps to prepare your API specification:
.. Sign up for Anypoint Platform:
+
https://anypoint.mulesoft.com/login/\#/signup[https://anypoint.mulesoft.com/login/#/signup]
.. Log into Anypoint Platform and click *Design Center*.
.. Create a new API specification project by clicking *+Create* in the top-right corner and selecting *API Specification*.
.. In the *New API Specification* dialog, specify a name for your project, select *Start with API Designer*, and click *Create*.
.. On the left side of the screen, click the action menu (the three-dot icon) at the top of the file list and select *Import*.
+
* If you want to import a RAML file, select _File or ZIP_ or _URL_.
* If you want to import a Swagger/OAS file, select _OAS File or ZIP_ or _OAS URL_.

+
API Designer converts Swagger/OAS files to RAML. If any errors are reported during the conversion, address them by following the instructions in the error messages.
.. After importing, test your API to make sure it works as you expect it to.
... In the top-right corner of the screen, switch on the mocking service.
... In the file list, select your API specification.
... In the API summary on the right side of the screen, expand the *Resources* entry until you see the methods for your resources.
... Click one of the methods.
... Review the information about the method.
... Click *Try It*.
... If the endpoint requires parameters, specify values for them.
... Click *Send*.

+
The results of the test of the method appear on the right side of the screen under the *Send* button.

. After your API specification is ready, save it in a git-compatible repository, such as GitHub or Bitbucket.

. Contact your Mulesoft BD counterpart and follow these steps:
.. Sign the Technology Partner Agreement (provided by your MuleSoft BD counterpart)
.. Ask for an extension to the expiration date of your trial of Anypoint Platform.
.. Ask for an invitation to the Connectivity Assets Manager tool, a self-service certification tool for connectivity assets, and create a new Anypoint Platform account based on the invitation.
.. Schedule a short demonstration to help MuleSoft understand your APIs and how they work in the Anypoint Platform.