= Upload an API Specification Created Outside of API Designer
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You cannot publish an API specification to Anypoint Exchange without going through API Designer. If you want to publish a specification that you have already authored outside of API Designer, you must create an API-specification project in API Designer, import your specification, and then publish to Anypoint Exchange.

== Before You Begin

Within Anypoint Platform, your user ID must be assigned the Design Center Developer permission.

== Procedure

. Open Design Center from the homepage of Anypoint Platform.
. Create an API-specification project that you can work in.
 .. On the *Projects* page in Design Center, click *Create* and then click *Create API Specification*.
 .. In the *New Specification* section of the dialog that is opened, name your project. You can change the name later, if you want to.
 .. Select the option *Text editor*.
 .. In the *Language* field, select the language in which your API specification is written.
 .. Click *Create Specification*.
 +
 *Result*: Design Center creates an API-specification project. In that project are two files:
* A default, blank specification that has the same name as the project. You can delete this file in a later step. Currently, it is set as the root file of the project, and it is not possible to delete a file that is set as the root file.
* A file named `exchange.json` that includes metadata that is required for Anypoint Exchange. This file is read-only.
 . Import your API specification.
 .. Click the gear icon in the top-right corner of the text editor and select *Import*.
 .. In the *Import* dialog, select *File or Zip*.
 .. Browse to your file or ZIP file and select it.
 +
 *Result:* The file or files are listed in the left pane of the editor. If you imported a ZIP file that contains files that are in a folder structure, the folder structure is represented in the pane.
. Set the root file of the project by right-clicking the specification and seleting *Set as root file*.
. Delete the blank specification that API Designer created by default.

== What To Do Next

Publish the API-specification project to Anypoint Exchange. See xref:design-publish.adoc[Publish an API Specification].

== See Also

xref:exchange::index.adoc[Anypoint Exchange]
