= About Accessing Design Center
ifndef::env-site,env-github[]
include::_attributes.adoc[]
endif::[]

You need to meet the following requirements for accessing Design Center, using its features, running and deploying apps, and publishing designs to Exchange:

* Be assigned the Design Center Developer permission or be the Organization Owner.
+
The user who first signs up for the Anypoint Platform organization is the Organization Owner.
+
* Be assigned to the CloudHub Admin role for the Design environment.
* Be assigned to the Exchange Contributor role.
* Belong to an Anypoint organization that has at least one CloudHub Design Environment with 0.2 vCores of available capacity.

To deploy to the production environment from Design Center, your user account also needs to be assigned to a CloudHub Developer role specifically for the production environment.

You need to be assigned multiple roles to have the same permissions in separate environments. To assign a set of roles to multiple users, you can create a custom role. Roles are assigned per environment.


== See Also

* xref:access-management.adoc.adoc::roles.adoc[Roles]

* xref:access-management.adoc.adoc::environments.adoc[CloudHub Environments]